### ISSUE TITLE
Capture Window not working anymore

### ISSUE THREAD

**Issue by Rouzax** [greenshot/greenshot#116]
**Describe the bug**
I believe this started to happen since my update to Windows 10 version 1803.
When ever I try to capture just window Greenshot will only select my entire screen, or if I move the capture to the Windows Taskbar it will capture that as a window. All other windows are not recognized and selected

**Expected behavior**
Select and capture only the window

**Screenshots**
![image](https://user-images.githubusercontent.com/4103090/54016206-7a9a5780-4182-11e9-9dfd-196e5b3507e3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 1803
 - Greenshot: 1.2.10 Build 6

**Comment by Rouzax** [comment]
Hmm,
After a reboot it started to work again but it seems to stop working after some time.

**Comment by TD-er** [comment]
I have issues too since a couple of days (3 weeks at most I guess)
It may take minutes for Greenshot to appear when pressing the PrntScr button.
Opening the context menu from the icon bar then also takes minutes to appear.
Killing Greenshot and starting it again will make it perform fast again.

Also if it has been used recently it reacts fast, but after some time (few hours) it will take minutes again to get some reaction from Greenshot.
I should be running the last released version:
![image](https://user-images.githubusercontent.com/3751318/54925847-735ba380-4f0f-11e9-8826-6039cd373752.png)

**Comment by Shockah** [comment]
Also having the same issue. Killing and starting explorer back again seems to fix it. Didn't figure out the cause yet though.

**Comment by Lakritzator** [comment]
When creating an issue here, there is an template which is clearly not read... we have a separate system for support & bugs from a users perspective.

That said... 

Can you make a list of tools / utilities you use? They might have influence on the way Greenshot works.

**Comment by Rouzax** [comment]
@Lakritzator, I'm used that all the tools I use do their issues on GitHub as well and I indeed missed that section in the Create Issue template, sorry.

I migrated to ShareX so can't really be of any help but this is my installes Sofwtare list

DisplayName | DisplayVersion | Publisher
-- | -- | --
Adobe Acrobat DC | 1.901.220.040 | Adobe Systems Incorporated
Adobe Creative Cloud | 4.9.0.504 | Adobe Systems Incorporated
Adobe Photoshop CC 2019 | 20.0.5 | Adobe Systems Incorporated
Adobe Refresh Manager | 1.8.0 | Adobe Systems Incorporated
Anchor for PowerPoint | 1.0.2 | PowerPoint Alchemy
Asmedia USB Host Controller Driver | 1.16.56.1 | Asmedia Technology
Brave | 77.0.68.138 | Brave Software Inc
ClickShare Extension Pack | 1.1.2.7 | Barco N.V.
DFUDriverSetupX64Setup | 1.8.0.0 | GN Audio A/S
FirmwareUpdater | 1.8.0.0 | GN Audio A/S
GO Contact Sync Mod | 3.10.53 | WebGear Ltd, New Zealand + Create Software + Stru.be...
Google Update Helper | 1.3.99.0 | Google Inc.
GoTo Opener | 1.0.527 | LogMeIn, Inc.
Intel(R) Chipset Device Software | 10.1.1.38 | Intel(R) Corporation
Intel(R) Dynamic Platform and Thermal   Framework | 8.3.10207.5567 | Intel Corporation
Intel(R) HID Event Filter | 2.2.1.364 | Intel Corporation
Intel(R) Processor Graphics | 26.20.100.6888 | Intel Corporation
Intel(R) Trusted Connect Service Client   x86 | 1.50.638.1 | Intel Corporation
Intel(R) Trusted Connect Services   Client | 1.50.638.1 | Intel Corporation
Intel(R) Wireless Bluetooth(R) | 21.20.0.4 | Intel Corporation
Jabra Direct | 4.0.5390.0 | GN Audio A/S
Jabra Direct | 4.0.5390.0 | GN Audio A/S
KeePass Password Safe 2.39.1 | 2.39.1 | Dominik Reichl
K-Lite Codec Pack 14.9.4 Full | 14.9.4 | KLCP
McAfee Agent | 5.6.0.702 | McAfee, Inc.
McAfee Data Exchange Layer for MA | 5.0.0.568 | McAfee LLC
McAfee VirusScan Enterprise | 8.8.013000 | McAfee, Inc.
Meld | 3.18.3 | The Meld project
Microsoft Azure Information   Protection | 1.41.51.0 | Microsoft Corporation
Microsoft PFE BasicMsiTest | 1.0.0 | Microsoft PFE
Microsoft PFE Remediation for   Configuration Manager | 14.7 | Microsoft Corporation
Microsoft VC++ redistributables repacked. | 12.0.0.0 | Intel Corporation
Microsoft Visual C++ 2005 Redistributable | 8.0.61001 | Microsoft Corporation
Microsoft Visual C++ 2005 Redistributable | 8.0.56336 | Microsoft Corporation
Microsoft Visual C++ 2008 Redistributable   - x86 9.0.30729.17 | 9.0.30729 | Microsoft Corporation
Microsoft Visual C++ 2008 Redistributable   - x86 9.0.30729.6161 | 9.0.30729.6161 | Microsoft Corporation
Microsoft Visual C++ 2010x86   Redistributable - 10.0.40219 | 10.0.40219 | Microsoft Corporation
Microsoft Visual C++ 2012 Redistributable   (x64) - 11.0.61030 | 11.0.61030.0 | Microsoft Corporation
Microsoft Visual C++ 2012 Redistributable   (x86) - 11.0.61030 | 11.0.61030.0 | Microsoft Corporation
Microsoft Visual C++ 2012 x86 Additional   Runtime - 11.0.61030 | 11.0.61030 | Microsoft Corporation
Microsoft Visual C++ 2012 x86 Minimum   Runtime - 11.0.61030 | 11.0.61030 | Microsoft Corporation
Microsoft Visual C++ 2013 Redistributable   (x64) - 12.0.30501 | 12.0.30501.0 | Microsoft Corporation
Microsoft Visual C++ 2013 Redistributable   (x64) - 12.0.40660 | 12.0.40660.0 | Microsoft Corporation
Microsoft Visual C++ 2013 Redistributable   (x86) - 12.0.30501 | 12.0.30501.0 | Microsoft Corporation
Microsoft Visual C++ 2013 Redistributable   (x86) - 12.0.40660 | 12.0.40660.0 | Microsoft Corporation
Microsoft Visual C++ 2013 x86 Additional   Runtime - 12.0.40660 | 12.0.40660 | Microsoft Corporation
Microsoft Visual C++ 2013 x86 Minimum   Runtime - 12.0.40660 | 12.0.40660 | Microsoft Corporation
Microsoft Visual C++ 2015-2019   Redistributable (x64) - 14.22.27821 | 14.22.27821.0 | Microsoft Corporation
Microsoft Visual C++ 2015-2019   Redistributable (x86) - 14.22.27821 | 14.22.27821.0 | Microsoft Corporation
Microsoft Visual C++ 2019 X86 Additional   Runtime - 14.22.27821 | 14.22.27821 | Microsoft Corporation
Microsoft Visual C++ 2019 X86 Minimum   Runtime - 14.22.27821 | 14.22.27821 | Microsoft Corporation
Nextcloud | 2.3.3.1 | Nextcloud GmbH
PhishAlarm Outlook Add-In | 3.2.22.0 | Proofpoint, Inc.
PhishAlarm Outlook Add-In Bundle | 3.2.22.0 | Proofpoint, Inc.
Plex | 1.0.0 | Plex, Inc.
Plex Media Player | 2.38.0 | Plex
PPTools THOR | 1.0.004 | Stephen Rindsberg dba PPTools
Python Launcher | 3.7.6762.0 | Python Software Foundation
Realtek Audio COM Components | 1.0.2 | Realtek Semiconductor Corp.
Realtek Card Reader | 10.0.17763.21313 | Realtek Semiconductor Corp.
Realtek High Definition Audio Driver | 6.0.1.8569 | Realtek Semiconductor Corp.
Realtek PC Camera | 10.0.15063.11292 | Realtek Semiconductor Corp.
Realtek USB Audio | 6.3.9600.208 | Realtek Semiconductor Corp.
Realtek USB Ethernet Controller   All-In-One Windows Driver | 10.32.328.2019 | Realtek
Samsung C1860 Series | 1.16 (28-7-2017) | Samsung Electronics Co., Ltd.
Samsung Printer Live Update | 1.01.00:04(2013-04-22) | Samsung Electronics Co., Ltd.
SpeedCrunch | 0.12 | SpeedCrunch
Teams Machine-Wide Installer | 1.2.0.17057 | Microsoft Corporation
Thunderbolt™ Software | 17.4.79.510 | Intel Corporation
WinSCP 5.15.3 | 5.15.3 | Martin Prikryl
Zoom | 4.3.46336 | Zoom
Zoom Outlook Plugin | 4.5.46881 | Zoom

**Comment by Simpuhl** [comment]
Same issue here, very annoying. Hoping for a fix

**Comment by Lakritzator** [comment]
@Simpuhl Do you have the possibility to try one of our more recent builds, which have not been officially released?
You can find them here: https://github.com/greenshot/greenshot/releases
For example at the time of writing the newest versions would be 1.3.178
We are constantly building new versions, just pick the newest on top of the list.

In the 1.3 versions of Greenshot I fixed a bug which MIGHT also solve this, see https://greenshot.atlassian.net/browse/BUG-2535 unfortunately, nobody confirmed this. I actually hate it when people report a problem, and don't answer questions or can't confirm if the fix helped. Anyway, the description was similar to this. And after placing a LOT of time in it, I found something which explained that some invisible windows were not ignored, and fixed this. So please let me know if that helps!

**Comment by Lakritzator** [comment]
Hint for others: It might have to do with virtual desktops, so if you have this issue let us know if this might be the case.

**Comment by Lakritzator** [comment]
@TD-er thanks for the hint. But it should not matter if how the display is connected, USB-C is just a way to transport a DisplayPort (DP) signal. I would expect it to be a different application / utility which causes some issues, and Greenshot just didn't know the right criteria to ignore something which was "on the screen" but was not rendered visibly. Unfortunately on that level there are some really obscure thing going on... I hope someone who has the issue can try Greenshot 1.3.178 or later, to confirm if the issue is gone. If not, I will need more information, I'm willing to write a specific tool, to troubleshoot this.

**Comment by TD-er** [comment]
I'm not really familiar to how DP does work at a low level.
But I guess the HP USB-C dock (HP 2UF95AA) does something with respect to frame buffering as both connected 4k displays were both running at 60Hz and as far as I understand that's not possible directly via the USB-C DP connection (not thunderbolt, but DP)

**Comment by Lakritzator** [comment]
@TD-er The window manager (specifically DWM) doesn't care much about the graphics subsystem under it. So whatever "buffering" is done, it doesn't suddenly turn up as a Window on the desktop covering other windows. Thankfully that is a detail which is not surfacing as things I additionally need to do to make Greenshot work. There is enough mysteries causing work already. 😅

**Comment by Simpuhl** [comment]
After I kill explorer, it works again for a while but eventually stops.

**Comment by Simpuhl** [comment]
> @Simpuhl Do you have the possibility to try one of our more recent builds, which have not been officially released?
> You can find them here: https://github.com/greenshot/greenshot/releases
> For example at the time of writing the newest versions would be 1.3.178
> We are constantly building new versions, just pick the newest on top of the list.
> 
> In the 1.3 versions of Greenshot I fixed a bug which MIGHT also solve this, see https://greenshot.atlassian.net/browse/BUG-2535 unfortunately, nobody confirmed this. I actually hate it when people report a problem, and don't answer questions or can't confirm if the fix helped. Anyway, the description was similar to this. And after placing a LOT of time in it, I found something which explained that some invisible windows were not ignored, and fixed this. So please let me know if that helps!
> 
> Btw. the current builds do not have code signing yet, so you need to jump trough some Windows hoops to get it installed.... "keep" the file after downloading, and look into the details of the popup windows if there is no install option.

I can try any build you like. I am currently using this one:

![image](https://user-images.githubusercontent.com/262571/113317009-cb2e0180-92c3-11eb-8959-9208e6bbdfb0.png)

**Comment by Simpuhl** [comment]
@Lakritzator

This is separate to this issue, if you want me to open a new ticket I can but in this new version, every time I capture a screenshot or click copy I get this error:

![image](https://user-images.githubusercontent.com/262571/113318038-dfbec980-92c4-11eb-8e50-a62397ba0ab0.png)


The odd thing is that its actually working fine, if the error itself didn't popup I would say no issues.
`Software version: 1.3.178 - 2fdb667d70 (64 bit)
.NET runtime version: 4.0.30319.42000+
Time: 2021-04-01 08:31:58 -07:00
OS: Windows 10 2009 x64 build 19042
GDI object count: 116
User object count: 143

Exception: System.UnauthorizedAccessException
Message: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

Stack:
   at Windows.UI.Notifications.ToastNotifier.Show(ToastNotification notification)
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotifierCompat.Show(ToastNotification notification)
   at GreenshotWin10Plugin.ToastNotificationService.ShowMessage(String message, Nullable`1 timeout, Action onClickAction, Action onClosedAction) in D:\a\1\s\GreenshotWin10Plugin\ToastNotificationService.cs:line 166
   at GreenshotWin10Plugin.ToastNotificationService.ShowInfoMessage(String message, Nullable`1 timeout, Action onClickAction, Action onClosedAction) in D:\a\1\s\GreenshotWin10Plugin\ToastNotificationService.cs:line 187
   at Greenshot.Helpers.CaptureHelper.SurfaceMessageReceived(Object sender, SurfaceMessageEventArgs eventArgs) in D:\a\1\s\Greenshot\Helpers\CaptureHelper.cs:line 563
   at GreenshotPlugin.Interfaces.SurfaceMessageEventHandler.Invoke(Object sender, SurfaceMessageEventArgs e)
   at Greenshot.Drawing.Surface.SendMessageEvent(Object source, SurfaceMessageTyp messageType, String message) in D:\a\1\s\Greenshot\Drawing\Surface.cs:line 1040
   at GreenshotPlugin.Core.AbstractDestination.ProcessExport(ExportInformation exportInformation, ISurface surface) in D:\a\1\s\GreenshotPlugin\Core\AbstractDestination.cs:line 109
   at Greenshot.Destinations.ClipboardDestination.ExportCapture(Boolean manuallyInitiated, ISurface surface, ICaptureDetails captureDetails) in D:\a\1\s\Greenshot\Destinations\ClipboardDestination.cs:line 75
   at Greenshot.Forms.ImageEditorForm.DestinationToolStripMenuItemClick(Object sender, EventArgs e) in D:\a\1\s\Greenshot\Forms\ImageEditorForm.cs:line 1284
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Configuration dump:
`

**Comment by warm-july** [comment]
Is there update on this issue, I'm having the same problem

**Comment by Lakritzator** [comment]
@warm-july Can you be more specific of your problem, and maybe add some information (Greenshot version, Windows version, any tools you use) which might help.

**Comment by warm-july** [comment]
> 
so similar to OP when I try to do window capture it still will only able to recognize my whole screen or maybe the taskbar at the bottom but not any software window, explorer, etc. Greenshot version is 1.2.10, Win10.0.19042. same issue both on my local work PC and on my work cloud PC. On work cloud PC it only has a few thing running like Microsoft Team, Autodesk desktop app, creative cloud app, NVIDIA and microsoft office stuff

**Comment by Lakritzator** [comment]
@warm-july Can you try out the next version of Greenshot, which is still work in progress, on one of your PCs where the issue occurs?
You can find it here: https://github.com/greenshot/greenshot/releases

Just get the most recent "unstable", which currently is "Greenshot 1.3.220 unstable Pre-release"

For details why I would like you to check, see here: https://github.com/greenshot/greenshot/issues/116#issuecomment-811686609
I have added more fixes since then, so the other issues in this issue should have been fixed too.

**Comment by warm-july** [comment]
@Lakritzator 
1.3.220 seems to solve this. When will this get shipped as a stable release? I'm using it on company machine and will have to wait for stable version.
Thank you!

**Comment by Lakritzator** [comment]
@warm-july it will come in the 1.3 release, there is still a lot of work to be done for a stable product.

Expectancy management: 
Greenshot is completely done in my free time for which I am not paid, that free time is little and I also do not have a lot of control over the when and how much (kid, wife, dog, house etc.). IF I give an estimate, I also want to deliver in that time, making it stress which has no benefit for me. If you need a clear shipping date and scope, take a paid product with a group of people behind it.

**Comment by warm-july** [comment]
@Lakritzator  thnx for the info!
I actually found that capture in window does work if I just press space after activating the window capture mode in current stable version, just for your reference.

**Comment by syousef1975** [comment]
As a temporary workaround, until this is fixed, "Capture window from list" still works correctly from the task bar dropdown if you can identify the window uniquely by its title.
