### ISSUE TITLE
[Feature Request] Tabbed view instead of multiple windows

### ISSUE THREAD

**Issue by p0izn** [greenshot/greenshot#12]
Could you please add an option to view all shots in a tabs of one window instead of multiple windows?
Thanks

**Comment by Lakritzator** [comment]
Thanks for reporting this, unfortunately the github issues should only be for code related issues, still looking to see how I can make that clear...

Please follow this feature here: https://greenshot.atlassian.net/browse/FEATURE-519
(Yes, it is older, but I am working hard on making it happen...)

**Comment by Lakritzator** [comment]
Found it... now when reporting am issue a message is shown, sorry for the confusion.

**Comment by Lakritzator** [comment]
See: https://github.com/greenshot/greenshot/blob/develop/CONTRIBUTING.md

And like I said, follow: https://greenshot.atlassian.net/browse/FEATURE-519
