### ISSUE TITLE
Brackets (feature request)

### ISSUE THREAD

**Issue by lamuzzachiodi** [greenshot/greenshot#133]
Ok, may be this ins't the right place for feature request, but anyway, i want suggest you add curly brackets to available items like arrows, numbers. etc. Why?. If you want to group many items instead a bunch of arrows you simply put a bracket. That's all. Thanks for you job.

**Comment by Lakritzator** [comment]
Thanks for using and supporting Greenshot.

When creating an issue here on GitHub, there is a HUGE notice for what this issue tracker should be used. As this doesn't seem to be a code related issue, but a plain feature request you seem to have ignored this. Please report this on https://greenshot.atlassian.net

I apologise if this seems rude, but we have a bit more than 10 users... and having work spread all over the place doesn't help us.

Also do add some examples in the description, as the description doesn't really help me to understand what you want to do.
