### ISSUE TITLE
Unable at .Net framework-4.8 after install

### ISSUE THREAD

**Issue by ALTanir** [greenshot/greenshot#137]
Please, submit a new release for new or latest positions on Win.OS . No more version found after [1.2.10.6](http://getgreenshot.org/version-history/). When I clicked shortcut to open- it seems 
![ERRORs](https://user-images.githubusercontent.com/10827600/63204801-75d8b880-c0bd-11e9-8053-8c32a1d490b0.JPG) (Problem of missing a file).
So then tried up solve manually **by download. But next starting requires more** similar files missing. So check it on .Net framework-4.8 . This is very important while more software is not found like this best and top granted.
_### Another feedback- I always use it for an functional option only_ and nothing more to use. It is image quality-analyze option such on every captures. I want high or low quality to use. Other more options unwanted I want to disable and will run on its default selection. So settings need option to disable such as pc-RAM will function speedy. Others, Win.OS has system-app to get but quality-analyze option needs for me . This I telling you- but not a very important. More request having to say is already OK by default.
Thank you

**Comment by Lakritzator** [comment]
I'm not sure how to understand your issue, you really don't supply us much information so we can only guess. I'm guessing your PC is somehow modified, as you seem to focus on RAM usage. Maybe you de-installed the Visual C++ runtime from your PC...?

Anyway, you should be reporting this on our Jira, as was told in our template.

**Comment by ALTanir** [comment]
Yes, thanks. I found my OS-setup have detected with some unsupported formula, So more apps were showing some error. And after a new setup no problem detects now. I am sorry for make you a tension.
