### ISSUE TITLE
Capture Screen

### ISSUE THREAD

**Issue by elig0n** [greenshot/greenshot#140]
I would like to see a Capture Screen/Monitor option . I use two monitors and want to capture a specific desktop.

**Comment by foxx1337** [comment]
Press print screen, then press space and you'll see the overlay extend to the whole screen with the mouse on. Just move the mouse to the screen you desire and click it.

**Comment by foxx1337** [comment]
Move the mouse to the desired screen and press ctrl + print screen.

**Comment by Lakritzator** [comment]
@foxx1337 has answered this correctly, thanks for that.

This issue doesn't really belong here... so closing it.
