### ISSUE TITLE
Allow to chance canvas size

### ISSUE THREAD

**Issue by c33s** [greenshot/greenshot#141]
sorry for reporting a feature request here. have an github account but no attlassian account :)

if i take a screenshot from a non quadratic logo it would be nice if i can resize the image canvas (taking this term from photoshop) directly in greenshot. 

currently i have to open photoshop to create a 300x300px image from a 40x300px image even if i only want leave the image alone (do not change the size of the main image) but change the canvas and add white or keep transparent background.

**Comment by Lakritzator** [comment]
This feature request is already open there, closing this.
You are more than welcome to create an Atlassian account, and vote over there.
