### ISSUE TITLE
Please add Greenshot for mac to the github releases

### ISSUE THREAD

**Issue by c33s** [greenshot/greenshot#146]
on your website you write "Only $1.99 to cover our own costs!". my request is not about getting it for free, if you have to pay for an osx sdk or whatever, simply forget this request.

but if the payment is only required to have the comfort to download and install it via the appstore, i ask you to add the osx binary to your github repos release page

(its not about giving you no money, its about not giving data to apple!)

**Comment by creeloper27** [comment]
Any update?

**Comment by cjohnsonuk** [comment]
I used this instead on Mac.  Its about as close as it gets http://snappy-app.com/

**Comment by RSully** [comment]
How about simply build instructions for macOS?

**Comment by Lakritzator** [comment]
Greenshot for OSX is a completely different product, this repository doesn't contain any code for that. We might move these together in the future, but we didn't decide on the how and when.

I want to point out that we could not make Greenshot without financial backing, there is a lot of effort needed to maintain both the Windows and Mac OS versions. We are not talking about an hour a week, I myself spend ~8-15 hours a week on answering questions, maintaining our website, contacting translators, fixing bugs, writing new features for future versions and looking at how we can make Greenshot work with the next Windows/.NET versions. One of the harder things of a tool like Greenshot, is that it needs a deeper OS integration.

Greenshot for Windows is backed by donations and a bit of ads, and Greenshot for OSX is backed by the revenue from the app store. It's an unfortunate fact. We would not be able to bring up the time to keep Greenshot working or move forward, if there is no money in it for us, we could spend that time on other things which would either save us money or bring money.

As we will not add the mac version to github at this time, I'll close this issue.
