### ISSUE TITLE
Imgur History Not Working

### ISSUE THREAD

**Issue by EnragedN3wb** [greenshot/greenshot#148]
**Describe the bug**
Screenshots do not show up in Imgur History when not using "anonymous access".

**To Reproduce**
1. Uncheck "Use Anonymous Access" in Imgur Settings
2. Take screenshot
3. Log in to Imgur
4. Check History in Greenshot

**Expected behavior**
See screenshot in history.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: All

**Additional context**
This has been an issue for a very long time now for me persisting through multiple windows updates & complete drive formats + reinstallations.

**Comment by Lakritzator** [comment]
Sorry, I'm only responding now.
But our tracker is actually located here: https://greenshot.atlassian.net as was mentioned at the time your created this issue.

Although it might not be the most logical thing, this is the behavior as was designed. The history is only there so people can delete the anonymous uploads as those are not tracked elsewhere and was never created for the uploads which can be tracked with Imgur themselves.

Somewhere in the future there will be a much better generic history, but the current is not mend for that 🤷‍♂️
