### ISSUE TITLE
Mouse Cursor is only captured on left screen in dual monitor setup

### ISSUE THREAD

**Issue by sunsero** [greenshot/greenshot#149]
See title - the mouse cursor is only captured when it's on the left screen (when sending full screen screenshot with CTRL+PrtScr to the Greenshot editor)

Windows 10 1903

**Comment by Lakritzator** [comment]
This is actually not the correct place, as you should have seen in the template when opening a bug here, but I fixed it for the next release anyway.

No current release date planned, I am closing it anyway.

**Comment by nepa** [comment]
+1
