### ISSUE TITLE
Github releases from Azure not tagged/released

### ISSUE THREAD

**Issue by leifcr** [greenshot/greenshot#151]
It seems like the azure artifacts are uploaded, but the release isn't done in the release pipeline. 
At least when looking at this pipeline:

https://dev.azure.com/greenshot/Greenshot/_releaseProgress?_a=release-environment-logs&releaseId=89&environmentId=89

A release is made, but the release isn't visible on github. Or is this because the 2.0 branch is still awaiting dotnetcore 3.0 fixes?

**Comment by Lakritzator** [comment]
Hi,

the builds are currently not yet good enough for "general public", even to preview.

There are some main reasons besides it being somewhat unstable:
* dotnet core 3.0 was until a month ago in preview, and a feature was not finished. This feature is unfortunately not coming until .NET 5.0, so I will need to reconsider.
* I have included telemetries, information on crashes etc which we need to improve our quality. And currently there is no opt-in (which it will be) or way to turn it off, this is not something I would like people to be confronted with.

So currently they are published as draft.

**Comment by leifcr** [comment]
Thanks for the info. I'll close the issue.
