### ISSUE TITLE
Can you please make the program as simple as possible?

### ISSUE THREAD

**Issue by Jonney3099** [greenshot/greenshot#155]
There're 100+ class in this project. I am not sure all of them are really necessary, otherwise, we will fall into bugs soon. 
Can you please simplify so that we can easily follow the project?

**Comment by Lakritzator** [comment]
I'm confused, what is your motivation for this request? Maybe you can elaborate a bit, tell us why?

**Comment by Jonney3099** [comment]
I means the source code of "Screen Capture" program is so complicated to follow though all classes are being written elegantly. If we count all of classes including "Dapplo" reference, there're over 1600+ files.  It's huge amount of coding work and also give us headache to read the codes.

**Comment by Lakritzator** [comment]
There is even more than that, if you look at all the dependencies.
But why would someone need to read through all the code, and who is us?

Although the transformation of Greenshot from an hobby project which started years ago, to a more professional product is still going on, the reason why having multiple classes have to do with principals like SOLID.

Some of the code, mainly for the addons, will be moved to different repositories as soon as the base is more stable.

It is a huge amount of coding work, but why would you want to read through all of the code?
