### ISSUE TITLE
Greenshot help as part of the repository

### ISSUE THREAD

**Issue by mischlrebl** [greenshot/greenshot#170]
The Greenshot help out of the application (F1) points to a part of the website no one external can edit.

If the help would be linked to a page as part of the repo, one could add pull requests with modifications and so help to keep it updated while relieve the developers.

**Comment by jklingen** [comment]
I like the idea, I think we should add a prominent link like "Help to improve this page" or similar.

Thanks for sharing your idea. 🙂

**Comment by mischlrebl** [comment]
perhaps it could be more easier to simply forward from the help (https://getgreenshot.org/help/) to a help.MD file here in the root of the repro where it can be maintained. 
needs less work on the homepage itself - just a redirect or only a link - and the help page can be prepared before.

**Comment by Lakritzator** [comment]
We in fact have our site on github, you can do a PR for changes!
It's in the gh-pages branch.

Still it's not as simple as you say, there are multiple translations and we also have multiple versions...
We do really need to consolidate the help files, we are shipping Greenshot with different files (for offline usage).

**Comment by mischlrebl** [comment]
oh, nice, good to know...
PR #183

**Comment by jklingen** [comment]
Sorry, for some reason I assumed it was obvious that the help files are on GitHub pages (which it is not, of course); and that your request was just about adding a link from the help page to the file in the repository. :see_no_evil: 

I think we should add such a link nevertheless, maybe it would help to have frequent improvements to our help files.

Anyway, thanks for the PR :+1:

**Comment by mischlrebl** [comment]
Sorry, and I was not able to link to that until the day before yesterday... but now it is all ok and done, that is important.

The links will be good for sure. Please add them by yourself to match the criterias. And probably one for the FAQs would make sense too.
