### ISSUE TITLE
Feature Request: Remove warning message when opening second instance

### ISSUE THREAD

**Issue by htcfreek** [greenshot/greenshot#171]
> This GitHub repository is for developers, if you want to request a feature for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/FEATURE/issues/filter=allopenissues

I don't have an account for this portal. That's why I wrote my feature request here on github....

**Is your feature request related to a problem?**
At forst login or when I change user without log out, greenshot is showing the following message: "An instance of Greenshot is already running (...)" (I have to say that greenshot ist set for autostart via registry under HKLM.)
It's not a bug but the message is unnesesary for the user because the program is running already.

**Describe the solution you'd like**
Pleas remove this warning message and close the new instance silently.
To allow the error analysis you could write an information about this into the log file: "User want to open seccond instance: process-ID, path, user kontext"

**Describe alternatives you've considered**
1. Adding a preference in greenshot.ini to allow hiding this warning message.
2. Showing the warning message only if both instances running in the same userprofil. (Makes only sence if two greenshot instances can running in different profiles at the same time.)

**Additional context**
Picture of greenshot's warning message:
![image](https://user-images.githubusercontent.com/61519853/75615157-a9060500-5b40-11ea-9c67-40211de1a0e6.png)

**Comment by jklingen** [comment]
Thanks for taking the time to thoroughly describe your suggestion, we really appreciate that.

We would appreciate it even more if you took the time to sign up in our Jira. It is free and takes about 2 minutes.

You obviously read our text about where to create feature requests and bug reports, and decided not to care. You see, there is a reason why we are asking for this, let me explain: we are just a small team running Greenshot completely in the little amount of spare time we have beneath our full time jobs, families, homes, etc. Communication already takes a considerable part of the time we put into this project. Having features being requested across various channels causes a lot of duplicates and makes it very hard for us to keep track of requests, which eats a lot of additional time. Time we would rather spend with actually improving Greenshot than with searching for a specific message in multiple places or cleaning up duplicates.

Thanks for considering.

**Comment by htcfreek** [comment]
I have opened an official feature request for this on jira now: [FEATURE-1242](https://greenshot.atlassian.net/browse/FEATURE-1242)

**Comment by jklingen** [comment]
Thank you very much, highly appreciated :bow:
