### ISSUE TITLE
url

### ISSUE THREAD

**Issue by Swatchel** [greenshot/greenshot#175]
This GitHub repository is for developers, if you want to report a bug for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/BUGS/issues/filter=allopenissues

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
url http://download.microsoft.com/download/WindowsInstaller/Install/2.0/W9XMe/EN-US/InstMsiA.exe is unreachable now.
Please fix this url in your code

**Comment by Lakritzator** [comment]
The television doesn't work...

If I compare the sentence above, it has about the same amount of information as what you wrote.
Can you now fix the television?

I can assume that it might be something with our installer, but I don't like assumptions.
What version of Greenshot, what OS etc...
You completely ignored our template.

**Comment by jklingen** [comment]
Sorry, we cannot help you if you do not provide a clear and reproducible description of the problem.

Consider having a look at this https://getgreenshot.org/2013/02/07/constructive-feedback-is-always-welcome/ and give us more information if you are still having issues.
