### ISSUE TITLE
Fix for Editor visibility bug in release 1.3?

### ISSUE THREAD

**Issue by htcfreek** [greenshot/greenshot#179]
Hi everyone.

There is a problem with greenshot's editor where users can't open the editor's window in front of Microsoft Edge. This happens when the window of Microsoft Edge is maximized.

I have described it in [Bug-2570](https://greenshot.atlassian.net/projects/BUG/issues/BUG-2570).

Can you fix this also in release 1.3 of Greenshot?

Best regards.

**Comment by Lakritzator** [comment]
I saw the issue yesterday and I'm not sure why I need to have it here too.
