### ISSUE TITLE
Compile Windows version with CFG enabled 

### ISSUE THREAD

**Issue by asvc** [greenshot/greenshot#181]
**Is your feature request related to a problem? Please describe.**
Greenshot binary does not have CFG enabled.

**Describe the solution you'd like**
Enable [`/guard:cf`](https://docs.microsoft.com/en-us/cpp/build/reference/guard-enable-control-flow-guard?view=vs-2019) flag.

**Describe alternatives you've considered**
None that are relevant as Greenshot is already using MS Visual Studio to build/link.

**Additional context**
![image](https://user-images.githubusercontent.com/300146/79058978-b7088300-7cb3-11ea-90ce-f1aea0a886e8.png)

**Comment by Lakritzator** [comment]
Hey thanks for suggesting this, but as Greenshot is written for the .NET platform, which is managed code compiled to an intermediate language (IL) and interpreted & Just-In-Time (JIT) compiled by the runtime, there is no such flag.

Maybe with .NET 5, coming this year, this will be possible when we compile Ahead-Of-Time (AOT).

**Comment by Lakritzator** [comment]
btw... thanks for sponsoring, much appreciated!!!

**Comment by asvc** [comment]
You are totally right. Relevant: https://stackoverflow.com/questions/52295064/control-flow-guard-c-sharp#comment91537848_52295064
