### ISSUE TITLE
Shortcut-Translations editable in the Repro?

### ISSUE THREAD

**Issue by mischlrebl** [greenshot/greenshot#187]
Are the Shortcuts of the menu(s) editable - without Visual Studio - and when yes, where? thx

As the upload of an image here seems not to work: when clicking onto the Greenshot symbol in the notification area, at the top: Capture last region -> Umschalt + Druck

**Comment by Lakritzator** [comment]
What do you want to change? The hotkey combination is coming from the keyboard driver, it seems you are using a German (Austria?) keyboard..

**Comment by mischlrebl** [comment]
Then I wan't nothing change - I was not aware that the shortkey naming is coming from the OS language setting (Swiss German) despite the app language is set to English. 
thx
