### ISSUE TITLE
Greenshot on 4K monitors, very small window, not using Win10 scaling

### ISSUE THREAD

**Issue by Jezzper** [greenshot/greenshot#189]
As you can see from image Greenshot windows is very small on 4K monitor even if Win10 scaling is set to 150%, which scales other applications.

![2020-04-17 12_04_07-New Issue · greenshot_greenshot](https://user-images.githubusercontent.com/34474332/79557914-ab4a0180-80a3-11ea-841f-0b500341d961.png)

1) Would be great if Greenshot respected this Win10 scaling too
2) Would be very nice if Screenshots had setting to always scale output to a certain max width/height otherwise screenshots get very big for user not using 4K monitors, and would be a great feature in general

**Comment by jklingen** [comment]
Please refer to our JIRA, which is the place intended for bug reports and feature requests.
We are aware of that issue, see https://greenshot.atlassian.net/browse/BUG-1873

As a workaroudn for now, it might help to increase the editor icon size, as suggested in the comments of the mentionend bug.
