### ISSUE TITLE
Feature requests: Auto apply effects

### ISSUE THREAD

**Issue by rchovan** [greenshot/greenshot#19]
Hi, 
could you please implement auto apply effect feature ? 
Old feature requests are here: [https://greenshot.atlassian.net/browse/FEATURE-456?jql=text%20~%20%22effect%22](url)

Thank You

**Comment by Lakritzator** [comment]
At the moment you created this issue, you should have read the contributing information: https://github.com/greenshot/greenshot/blob/develop/CONTRIBUTING.md

Our JIRA is the place for featute request, the Github issues are just for code issues (developers only), follow the feature request here: https://greenshot.atlassian.net/browse/FEATURE-548

It is not forgotten... we are losing a lot of time moving to .NET 4.x, coping with e.g. Sourceforge & Imgur problems, and trying to relocate our website.
