### ISSUE TITLE
ClickAction options on the tray icon

### ISSUE THREAD

**Issue by mischlrebl** [greenshot/greenshot#195]
which other options are available for these setting in the ini? thx

; Specify what action is made if the tray icon is left clicked, if a double-click action is specified this action is initiated after a delay (configurable via the windows double-click speed)
LeftClickAction=SHOW_CONTEXT_MENU
; Specify what action is made if the tray icon is double clicked
DoubleClickAction=OPEN_LAST_IN_EXPLORER

**Comment by Lakritzator** [comment]
https://github.com/greenshot/greenshot/blob/release/1.3/GreenshotPlugin/Core/CoreConfiguration.cs#L49

**Comment by Lakritzator** [comment]
RightClick is always "SHOW_CONTEXT_MENU", so you can change the left & double click actions only.

**Comment by mischlrebl** [comment]
thanks a lot

**Comment by mischlrebl** [comment]
a CAPTURE_REGION by default on the left button would be cool!
