### ISSUE TITLE
Capture region issue

### ISSUE THREAD

**Issue by BercziSandor** [greenshot/greenshot#196]
**Describe the bug**
There is a bug in the function 'Capture Region': the picture with the selector is 1.5-2x bigger than before on the screen.

**To Reproduce**
1. Activate Capture Region function (default: button PrntScreen)
2. See error

**Expected behavior**
The preview area should be of the same resolution as before, on the screen.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: NA
 - Version: 1.3.75 unstable

**Additional context**
This bug is only in the new version.
I have two monitors, with the same resolution (1920x1080)

**Comment by asvc** [comment]
I presume you have misclicked. Issue body is the default template without any sign of necessary amendments.

**Comment by Lakritzator** [comment]
No, there was a bug in 1.3.75, fixed it in 1.3.76

Thanks for reporting it...
