### ISSUE TITLE
Screen region selection entry point is not accurate; lags start point

### ISSUE THREAD

**Issue by FalconFour** [greenshot/greenshot#197]
This GitHub repository is for developers, but since the Jira system is currently broken (500 error) and requires an Atlassian login, it really ought to be the other way around, with GitHub for user reported issues and Jira for developers that like stabbing themselves in the eye with the rusty fork known as Jira. So it is here, instead :)

**Describe the bug**
When making a screenshot selection, the "pickup" of the selection from the cursor is lagged, which frequently results in missed corners of selection boxes, requiring a re-take to correct. This happens when moving the mouse quickly, not when making a slow movement.

**To Reproduce**
1. Press PrtScrn key
2. Identify a region of the screen
3. Quickly in one action, move cursor to the region, click and drag a bounding box to select the region, but don't release it yet
4. Observe that the starting corner of the bounding box is not in the expected location

**Expected behavior**
As tested with MS Paint and countless other pieces of software, that the selection begins at the start point as intended, no lag between click-start and where the selection activity actually begins.

**Screenshots**
![image](https://user-images.githubusercontent.com/2126952/80003341-bc18bf80-8475-11ea-85ef-c8d59bcb4799.png)
![image](https://user-images.githubusercontent.com/2126952/80004100-c7b8b600-8476-11ea-9036-1b7c8f403984.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909, x64 (has been an issue for about a year, preceding these versions)
 - Browser: I like to use Firefox but this doesn't seem like a relevant point
 - Version: 1.2.10 build 6 (64-bit)
 - Device: Dell Latitude 5580, 7th gen i7 CPU, Alps touchpad chipset, Intel primary GPU with nVidia secondary.

**Smartphone (please complete the following information):**
 - Device: wait why is iPhone the default form field here lol
 - OS: oh right this is the smartphone field... is greenshot on phones too?
 - Browser: haha this field is missing a colon
 - Version: this one too, sorry i had to add some humor here to try bringing a smile

**Additional context**
I love Greenshot and hope to help improve it if just in some slight way. 👍

**Comment by asvc** [comment]
>  since the Jira system is ~currently~ broken (500 error) and __requires__ an Atlassian login

Yeah...

Now, speaking of the bug itself, I can't reproduce it here, also using nVidia GPU. Let's start with the following, in this order:
1. Install latest Greenshot build &mdash; v1.3.75
2. Install latest "studio" version of GPU drivers
3. Ensure that nVidia GPU is being used exclusively, not via "Optimus", etc.
4. Check that Dell power profiles that trade performance for battery life are not used
5. Confirm GPU is free via `nvidia-smi`
6. Attempt to reproduce the bug

**Comment by Lakritzator** [comment]
Also you might have the bad update check bug, disable the update check in the settings, restart and try again...

There was an issue that our update check was hanging and slowing Greenshot down.

We already made some changes on the server, but I'm not confident that the update check never hangs...

**Comment by FalconFour** [comment]
> using nVidia GPU

Well, see, that's the problem... can't directly use the nVidia GPU on a hybrid-graphics system. Let's just delete the nVidia GPU from the equation and assume I don't have an nVidia GPU at all (which is the god's honest platform-level truth, it's just a compute/render device really; the Intel GPU is the one directly driving the display).

Strange that you can't reproduce it. Just a simple whip-click, as fast as you can, doesn't end up starting the box in the wrong position? I don't mean a lag of seconds, I mean an instantaneous lag on the millisecond scale. So I wouldn't imagine an update server issue would do it ;)

But for completeness (thank you for trying!), I'm updating to 1.3.75 as I type this.

Okay, now things are worse. It doesn't seem to be DPI-aware... or at least, the execution path from the installer led it to be not DPI-aware. Upon hitting PrtScrn, the whole screen is enlarged showing only the upper-left corner of content, cropping out the bottom and right edges of the screen from the display view. That's definitely an issue, but hopefully one you're already aware of. :) (if not, I'm running 1920x1080 at 125% scaling)

I poked around and found the latency issue to be less prevalent, and the latency I can see is also reflected in MSPaint as well this time. So this may be fixed or just a figment of my imagination at this point. It bugs me to no end that PC touchpads get worse and worse over the years instead of getting better... I live my life on touchpads and they used to be good. ¯\_(ツ)_/¯ oh well. My rage is likely better aimed at Alps at this point.

**Comment by Lakritzator** [comment]
I just fixed, at least I hope, the DPI issue.
There was an error in the manifest file, which specifies how DPI is handled.

https://github.com/greenshot/greenshot/releases/tag/v1.3.76
