### ISSUE TITLE
Bullets only make the circle bigger. Not the number

### ISSUE THREAD

**Issue by Rasmus-Riis** [greenshot/greenshot#205]
This GitHub repository is for developers, if you want to report a bug for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/BUGS/issues/filter=allopenissues

**Describe the bug**
Bullets only make the circle bigger. Not the number

**To Reproduce**
1. Make a bullet (The red dot with numbers you can place in the picture)
2. Try to make it bigger by dragging the corners.
3. Watch in amazement that the circle gets bigger, but not the numbers; Rendering it unusable for large screenshots

**Expected behavior**
That the number grows in size with the circle

**Comment by Lakritzator** [comment]
Our 1.3 builds (currently "unstable") now support this, the feature will generally be available as soon as we release.
