### ISSUE TITLE
Upload to Imgur fails silently

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [greenshot/greenshot#211]
This GitHub repository is for developers, if you want to report a bug for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/BUGS/issues/filter=allopenissues

**Describe the bug**
'Upload to Imgur' seems to do nothing, even with my firewall disabled.

**To Reproduce**
Example steps to reproduce the behavior:
1. Press the hotkey that runs the program.
2. Make a screenshot.
3. Choose 'upload to Imgur'.
The result is: nothing at all. The Greenshot menu disappears, nothing else from the Greenshot program appears, and nothing happens with my browser.

**Expected behavior**
I expect an upload to Imgur.

**Additional information**

My browser is Firefox. I had it open at the time that I first experienced the problem and also when I reproduced the problem successfully. I had not tried to use the upload to Imgur function before.

**Versions (please complete the following information):**
 - Greenshot version: 1.2.10 build 6 (x64)
 - Windows version: Windows 10 Pro 1906 (18363)

**Comment by Lakritzator** [comment]
Hi,

Greenshot uploads the image to imgur, what do you expect to happen after that?
A link is pasted to the clipboard, so you can paste this in an email or social media.

If you were using the anonymous upload, there is a very simple history which allows you to view the uploads. You can find it under the context menu, with Imgur.

If you were using imgur credentials, you will find your uploads in Imgur itself, no need to supply something for that as it's already there,

Best wishes,
Robin

**Comment by LinuxOnTheDesktop** [comment]
Thanks for the reply. Are you saying both of the following two things?

1. What Greenshot does when you tell it to upload to imgur is: does the upload; puts the URL on the clipboard; gives the user no other indication - no direct indication - that anything has happened.
2. 1 is by design.

**Comment by Lakritzator** [comment]
Well, Greenshot should show a notification, but this might be turned off by you or the system.
So you might want to check that. If there is a notification, you can click it to get to Imgur right away.

Besides that, it's pretty much what you describe.

**Comment by LinuxOnTheDesktop** [comment]
Ah. I see the notification - just about. It appeared in the opposite area of the screen to where the Greenshot menu had appeared (the former was top-left, the latter bottom-right) and it disappeared after approximately - perhaps less than - one second. I see an option within Greenshot to enable notifications but nothing to control how they work.

**Comment by Lakritzator** [comment]
If you have the imgur uploads on "use anonymous access" your captures are visible in the imgur history, you can excess this from the context-menu "Imgur" -> history. It SHOULD copy a link to the clipboard, unless you have your settings in such a way that the picture is ALSO copied to the clipboard. (This is possible by modifying the destinations in such a way that both destinations are selected).
If you don't use anonymous access, your screenshots are NOT in the history, and should be visible inside Imgur.
Why did we do it like that? Well currently the only reason for the history is to store the "delete" link, we didn't have the aspiration to manage your screenshots for you. This is something we do consider for the future, managing them on a more global Greenshot level.
If you have issues with this, please look in your logs:
https://getgreenshot.org/faq/where-can-i-find-greenshots-log-file/
Maybe you can find something there?

**Comment by Lakritzator** [comment]
Btw... the reason for this slow response, the issues in the project are as mentioned while creating the issue only for developer to developer communication. This is a more generic bug / support question.
