### ISSUE TITLE
Ctrl+Shift+C shortcut does not work

### ISSUE THREAD

**Issue by subbame** [greenshot/greenshot#213]
Ctrl+Shift+C shortcut does not work anymore for me.

Greenshot-RELEASE-1.2.10.6
Greenshot 1.2.10.6-c2414cf RELEASE

**System:**
OS: Windows 10 Pro
Version: 2004
OS Build: 19041.264

**Comment by Lakritzator** [comment]
You ignored our template, and this is not where we track user problems (as was specified).
Please report this in our Jira https://greenshot.atlassian.net

Btw. I doubt I can do anything, there is no reason for it to suddenly not work anymore.
So I advice you to check what you recently changed to your system.
