### ISSUE TITLE
Paste JPEG image appear to have the wrong mime type

### ISSUE THREAD

**Issue by laurent22** [greenshot/greenshot#214]
**Describe the bug**

Pasted JPEG images have the mime type `image/jpg`, which is not a valid mime type and can cause issues in some applications. In particular it was reported to me on this issue: https://discourse.joplinapp.org/t/bug-while-testing-the-new-edit-ressources-functionality-in-1-0-218/9266/3?u=laurent

The valid mime type is `image/jpeg`, which should be better supported by most applications (granted, many applications will also support "image/jpg", including mine once I fix it, but it will avoid some issues if it's correct from the start).

See here for more info: https://stackoverflow.com/a/37266399/561309

**Comment by Lakritzator** [comment]
Hi, I finally got some time to look at this.
I'm a bit confused, how is Greenshot passing a mimetype? There is no to me known location where I pass a mimetype outside of any HTTP related code. To be honest, and this surprised me at bit, it seems Greenshot can't even paste jpg at all. It's a format which will loose transparence and caused some issues with Office applications.

How do you preproduce the issue?

Best wishes,
Robin

**Comment by laurent22** [comment]
I don't know to be honest, I was passing on the information I got from a user, who pasted an image from Greenshot to Joplin.

I didn't verify if I could replicate it, I just added code to my app to handle image/jpg

If it can't be replicated then feel free to close the issue.

**Comment by mgrandi** [comment]
Just noticed this when looking at the issue list, i was wondering if this was an issue with how greenshot was copying the data to the clipboard, but i downloaded a clipboard viewer (https://www.freeclipboardviewer.com/) and i don't see it having an entry that has image/jpg or anything like that

**Comment by Lakritzator** [comment]
I think that most likely the application that @laurent22 wrote takes the "clipboard format" and makes a mime type of it.
Closing this, as I don't see an issue here.
