### ISSUE TITLE
Size of counters

### ISSUE THREAD

**Issue by Rasmus-Riis** [greenshot/greenshot#220]
Please let it be possible to change the size of the numbers in the counters. As is now it is makes it impossible to read on large captures..

**Comment by Lakritzator** [comment]
I normally don't work on issues with this little, as I might change something which is not requested.
This might be the case, with the chance I just made... I made a change which calculates the size of the font used to draw the number of a counter based upon it's size. Maybe not exactly what you want, but that was the easiest change.

**Comment by Lakritzator** [comment]
If you want something else, and you cannot work on the code yourself, please use our JIRA as was described when you opened the issue. I'm closing this now, the change will be available in the next build of Greenshot.

**Comment by mischlrebl** [comment]
nice! when editing the counter part, wouldn't you fix that as well? https://greenshot.atlassian.net/browse/BUG-2585

**Comment by Lakritzator** [comment]
You would almost think that, unfortunately it's not so easy. For something with text, like that label, we need a lot of work to contact all translators. We always try to prevent UI changes, where possible. Especially when it's something on such a visible location.

Sorry, that will have to wait.
