### ISSUE TITLE
Imgur deletion not deleting

### ISSUE THREAD

**Issue by Dummy101** [greenshot/greenshot#24]
Deleting an image that has been captured and uploaded to imgur does not delete the image from the imgur server.

Steps to reproduce:
1) Make a capture and upload to imgur
3) Visit link as, for example, https://imgur.com/QfzkXwm (instead of https://i.imgur.com/QfzkXwm.png)
4) Delete the uploaded image via Greenshot's Imgur history dialog
5) Refresh the link and the image is retained.

Is there a solution?
Thanks

**Comment by Lakritzator** [comment]
This Issue tracker is not for such things, it's only code related! See here: https://github.com/greenshot/greenshot/blob/develop/CONTRIBUTING.md
We have an issue tracker for users.

Still.. did Greenshot remove the entry from the history?
Just in case, please copy greenshot.ini (see here on how to find it: http://getgreenshot.org/faq/where-does-greenshot-store-its-configuration-settings/) and greenshot.log (see here on how to find it: http://getgreenshot.org/faq/where-can-i-find-greenshots-log-file/) , this might contain the delete -hashes which are needed and might also hint on what when wrong.

Have a look in the greenshot.log, or attach it to an ticket, so we can have a look at it.

P.S.
Imgur is not know to be the most stable API :(

**Comment by Dummy101** [comment]
Thanks for your response.
I've created an issue at atlassin: https://greenshot.atlassian.net/browse/BUG-1949

**Comment by Lakritzator** [comment]
Continueing in BUG report (Imgur seems to respond wrong to the delete API, maybe they changed something AGAIN)
