### ISSUE TITLE
Obfuscating things for big font still readable

### ISSUE THREAD

**Issue by trivalik** [greenshot/greenshot#248]
**Describe the bug**
If you try to use "obfuscating things" on font like Arial with size 20. The text can be still read. If font is bold this effect is bigger.

**To Reproduce**
Example steps to reproduce the behavior:
1. Capture image of text with font size 20.
2. Open Editor
3. use Obfuscating things on font
4. obfuscated text can still be read

**Expected behavior**
text is not that easy to read

**Screenshots**
example text in Arial 20, bold
![hide_sensible_data](https://user-images.githubusercontent.com/3148279/91520423-91dc8000-e8f5-11ea-81dc-a66b8530059d.png)

**Versions (please complete the following information):**
 - Greenshot version 1.2.10 Build 6 (64 bit)
 - Windows version Windows 10 1809

**Additional context**
This function is good, but not if others can read it.

**Comment by Lakritzator** [comment]
Increase the pixel size, as is mentioned in the [help](https://getgreenshot.org/help/#editor-obfuscate)
