### ISSUE TITLE
Zoom while editing is needed

### ISSUE THREAD

**Issue by Layarion** [greenshot/greenshot#25]
Using the beta

I'm trying to Draw a rectangle around a very small letter in the cleanest, aligned, and sharpest looking way possible...

but i am having a hell of a time because the 8 black re-sizing blocks make it impossible to see what i'm doing. please for the love of god, allow me to zoom in OR give me a magnifier just like when i'm taking screenshots.

**Comment by Lakritzator** [comment]
https://github.com/greenshot/greenshot/blob/develop/CONTRIBUTING.md

Please monitor the ticket here: https://greenshot.atlassian.net/browse/FEATURE-84
(yeah it's old... but we want to rewrite the editor and than it's in it)

**Comment by gardian12** [comment]
Hello together,
I like to renew the request as described in [https://greenshot.atlassian.net/browse/FEATURE-84](url).
This would be very helpful in many cases.
Is there any chance to prioritize this?

**Comment by Lakritzator** [comment]
@gardian12 Thank you for your interest in Greenshot.

Unfortunately it's not helpful for us to have people reporting or "pinging" for issues / status and priority in multiple places. The issues here at GitHub are for developer / technical code issues.

You can if you think it helps, add your comment to FEATURE-84 like "what is the status"... or "I find this also important".

But:
We still have a huge backlog transforming our application to modern technologies which will be easier to maintain or make it easier for others from the community to support us.

I work on Greenshot in my free time, which is defined by the time I don't work and not spent with my family, limited by the amount of chores I need to do for my house, garden, car etc.

Freeing up time, to speed up the development, is only possible if I work less or have to do less chores -> this is only possible if Greenshot makes more money. As Greenshot is free, and a lot of companies don't donate, we only get a limited amount -> we can only slowly go forward.

We are looking at solving this, one way would be: https://opencollective.com/greenshot
These ways to help us free time, are available under the "Sponsor" button at GitHub. Currently it's not possible to sponsor a single person as I'm still on the waiting list.

There is not really a way to prioritise this, unless someone from the community says "here is a pull-request" for this feature. I really need to get rid of technical debts, meaning we use technologies which are no longer supported or block us to go forward. So I first want to have a running & stable Greenshot, with dotnet core 3.0, before I will add or change features. Dotnet core 3.0 is still in preview and will not be available before September, meaning there most likely won't be new version of Greenshot before that time. To be clear, there is also no guarantee that I will be able to finish before that time. "Greenshot is as is, and comes when it comes."

Btw. You can pretty much see the project is active here, but it could be better:  https://github.com/greenshot/greenshot/graphs/code-frequency

You are of course more than welcome to assist!!

**Comment by KillyMXI** [comment]
@Lakritzator we need someone from maintainers to take a look into the Jira issue and clear some things. Unfortunately, Jira is really inconvenient in this case, as it doesn't allow to bring your attention, so I'm writing here.

I would like to implement this feature, but before I try - I want to know your plans for the editor, to avoid wasted effort and money.

I see Greenshot is moving from WinForms to WPF. Is there any point to mess with legacy WinForms editor? Any ETA and details for what will come in place of it?
