### ISSUE TITLE
Icons are huge when on external monitor with normal DPI

### ISSUE THREAD

**Issue by awojtas** [greenshot/greenshot#258]
This GitHub repository is for developers, if you want to report a bug for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/BUGS/issues/filter=allopenissues

**Describe the bug**
The icons both on the Greenshot task tray menu and in the Greenshot screenshot editor are huge, 4x the size of normal.

**To Reproduce**
1. Use Dell XPS 15 with 4K screen on Windows 10
2. Have laptop closed and connected to external Dell dock
3. Have Dell 27" 2560x1440 screen connected to external Dell dock
4. Log onto Windows
5. Notice that Greenshot icons are messed up
This is the only application I've noticed any scaling issues with in Windows 10 now.

**Expected behavior**
I expect the icons to be a normal size. I often use this same Dell 27" screen connected to my work laptop, which has a normal 1920x1080 screen at 125% scaling. On that laptop Greenshot behaves correctly.

**Screenshots**
Greenshot menu, note the normal size of Android Studio and Windows Explorer in the background:
![image](https://user-images.githubusercontent.com/3030232/100189610-7a8f4c00-2f51-11eb-8bf0-754b7b71d663.png)

Greenshot editor:
![image](https://user-images.githubusercontent.com/3030232/100189644-909d0c80-2f51-11eb-8093-257c6396dd8e.png)

**Versions (please complete the following information):**
 - Greenshot version 1.3.122 232e20cb72
 - Windows Home version 20H2 x64

**Additional context**
I have tried every combination of the high DPI override settings on Greenshot.exe but nothing improves it.

**Comment by yisyang** [comment]
Similar issue here with greenshot editor. Except that icons on both top and left toolbars are TINY. Fortunately the text menu bar works just fine. 

Windows 10 (tried both Dev channel and Normal channel).
Desktop with external 4K monitors.
UI size @ 200%.

![Greenshot Editor](https://user-images.githubusercontent.com/5167456/100845322-e3833200-3431-11eb-8405-48ce9e7199a8.png)

![2020-12-01 23_57_28-Settings](https://user-images.githubusercontent.com/5167456/100844998-6bb50780-3431-11eb-8ef1-6640b17fb0f1.png)

**Comment by Lakritzator** [comment]
@yisyang Go into the settings, and change the icon size.

@awojtas due to laptop issues, I haven't been able to publish a new version of 1.3 where this should work much better.
Can't tell yet how long it will take to get a new one, pandemic / delivery and on top of that the investment was also hurting me...

**Comment by yisyang** [comment]
@Lakritzator Thanks and worked! Silly of me to not have thought of that.

![2020-12-02 00_56_54-Greenshot image editor](https://user-images.githubusercontent.com/5167456/100850903-5512ae80-3439-11eb-9789-712b56a80513.png)

**Comment by awojtas** [comment]
> @awojtas due to laptop issues, I haven't been able to publish a new version of 1.3 where this should work much better.
> Can't tell yet how long it will take to get a new one, pandemic / delivery and on top of that the investment was also hurting me...

Thanks for all your effort you've put into this app, the icon size isn't a showstopper and I still get great use out of Greenshot every day

**Comment by joachimmarder** [comment]
Same issue here, Greenshot has chosen 192 as default value for icon size.

> Go into the settings, and change the icon size.

After pressing OK, this exception occurred:

```
Software version: 1.3.139 - 5899d97ec2 (64 bit)
.NET runtime version: 4.0.30319.42000+
Time: 2021-01-30 13:48:33 +01:00
OS: Windows 10 1909 x64 build 18363
GDI object count: 158
User object count: 142

Exception: System.IO.FileNotFoundException
Message: Die Datei oder Assembly "Dapplo.Jira.SvgWinForms, Version=1.1.0.0, Culture=neutral, PublicKeyToken=5be96fed5d651fee" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.

Stack:
   at GreenshotJiraPlugin.JiraConnector.<>c.<.cctor>b__6_0(Object sender, PropertyChangedEventArgs args)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at GreenshotPlugin.Core.CoreConfiguration.set_IconSize(Size value) in D:\a\1\s\GreenshotPlugin\Core\CoreConfiguration.cs:line 295
   at Greenshot.SettingsForm.SaveSettings() in D:\a\1\s\Greenshot\Forms\SettingsForm.cs:line 487
   at Greenshot.SettingsForm.Settings_okayClick(Object sender, EventArgs e) in D:\a\1\s\Greenshot\Forms\SettingsForm.cs:line 518
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


```

**Comment by Lakritzator** [comment]
@joachimmarder I'll fix that in the next pre-release, one of my backing open source projects has split it's dlls into multiple, and this was forgotten in the installer. This is why the "FileNotFound"... My bad. 🤷‍♂️

**Comment by saulob** [comment]
Same error here, icons are huge. Even on the settings panel

I'm on a Tv, using 4k resolution and scale 300% (see attached picture)

![2021-03-24 12_36_34-Search](https://user-images.githubusercontent.com/3660977/112338663-bcc95f80-8c9d-11eb-8e3f-ffd4d0e53e9c.jpg)

![2021-03-24 12_38_30-Search](https://user-images.githubusercontent.com/3660977/112338848-e5515980-8c9d-11eb-91cb-e3ed6f57ddfe.jpg)

**Comment by awojtas** [comment]
Still unresolved in v194 both for task tray menu and the icons in app :(
This is on a 27" Dell at 2560x1440, 100% scaling. Dell XPS 15 laptop has internal 4K screen.

I connect a Dell 1080p laptop to this same screen via same USB-C dock running same Windows 10 build and it _doesn't_ have the scaling problem. So I think it is some kind of issue where the 4K screen, even if not being used, is affecting the scaling. 
Greenshot is the only app that exhibits this problem and it's painful.

![image](https://user-images.githubusercontent.com/3030232/114256640-b7467600-9a0e-11eb-8d5e-a1647e33a0dc.png)

![image](https://user-images.githubusercontent.com/3030232/114256647-d1805400-9a0e-11eb-95bc-d2fc1f240c3b.png)

**Comment by awojtas** [comment]
@Lakritzator settings is unusable, unsure what I should be changing:

![image](https://user-images.githubusercontent.com/3030232/114256723-77cc5980-9a0f-11eb-8a98-0d06c8643913.png)

**Comment by mischlrebl** [comment]
had this behaviour for quite some time as well - but not with 4k
quitting screenshot and starting again solved every time so far

**Comment by saulob** [comment]
It's bigger now, that's strange.

I'm using the latest version 1.3.201. 

![image](https://user-images.githubusercontent.com/3660977/119688072-0eb56f80-be1e-11eb-830b-92ea6e025202.png)

![image](https://user-images.githubusercontent.com/3660977/119687754-d2820f00-be1d-11eb-82c3-2ea57e2f657e.png)

![image](https://user-images.githubusercontent.com/3660977/119688134-19700480-be1e-11eb-9b9d-107712dc5db0.png)

**Comment by Lakritzator** [comment]
Check the icon size in the settings, it might be that I forgot to reset it, and if you already made them bigger, and Greenshot is automatically resizing, this might happen.

**Comment by saulob** [comment]
> Check the icon size in the settings, it might be that I forgot to reset it, and if you already made them bigger, and Greenshot is automatically resizing, this might happen.

Icon size? Where's it? Did not find anything about it

I tried to open the settings and got this error message

![image](https://user-images.githubusercontent.com/3660977/119692071-7b7e3900-be21-11eb-9ed1-6ff16f45d417.png)

**Comment by saulob** [comment]
> Check the icon size in the settings, it might be that I forgot to reset it, and if you already made them bigger, and Greenshot is automatically resizing, this might happen.

Fixed editing the icon size. Thanks

But no, I never used that option. I'm checking the option now, and every time I open the settings the icon size increases 

I saved with 16

![image](https://user-images.githubusercontent.com/3660977/119693145-65bd4380-be22-11eb-98f6-2b06700f3c81.png)

I opened it the settings again and the it's now 48. Strange. Save with 48.

![image](https://user-images.githubusercontent.com/3660977/119693323-8be2e380-be22-11eb-8ee3-3bd91ef81b8c.png)

Opened again and it's now 144. Really strange

![image](https://user-images.githubusercontent.com/3660977/119693500-b896fb00-be22-11eb-8363-e0c8bec8e523.png)

**I think that's the bug :)**

**Comment by saulob** [comment]
Everytime the settings is saved the value on icon size is multiplied by 3 

This is it

**Comment by Lakritzator** [comment]
Oops, will check

**Comment by Lakritzator** [comment]
Try 1.3.202 please: https://github.com/greenshot/greenshot/releases

**Comment by saulob** [comment]
Fixed for me, the "Icon size" value is ok now :)

Thank you

**Comment by Lakritzator** [comment]
Thanks for the feedback, closing this. If there are still issues, please let me know in a different issue so we don't confuse ourselves to much.

**Comment by icodeintx** [comment]
I have been unable to fix this issue locally.  The Icon Size is set to 16 the lowest it will go.  Greenshot is the only application on my computer that has this issue (that I've found).  

![image](https://user-images.githubusercontent.com/55411261/187828610-aeb48028-3063-4eb0-b6c5-6f74a536571e.png)

**Comment by bryndin** [comment]
The latest Greenshot 1.3.277  still has the same problem as @yisyang described. Tiny, virtually invisible toolbar icons in the editor, on the 4k screen with 250% scaling.   The context menu icons (right click on the G icon in the tray) are fine.

@Lakritzator Changing the icon size from 16 to 48 does increase the editor icons,  but it also 3x increases the context menu icons size and they look like what @awojtas originally reported.

It's Windows 11, 4k screen with 250% scaling.

**Comment by SvendK** [comment]
I understand this is an old thread, but it's one of the first hits on Google for: "greenshot" dpi problems so I thought I'd help. I'm running Windows 11 Pro if that's does anything.

I'm not sure if this fixes OP's and other's problems, as I haven't read it all, but this helped my DPI problems. If I captured something on my normal resolution (QHD, 100% DPI) screen and opened in the Image Editor, it would all look fine. If I then dragged the window over to my laptop's internal monitor, a 15" 4K resolution in 225% DPI, everything would get very small. And vice versa it would be very big. This fixed it:

Go to greenshot.exe folder (e.g. C:\Users\<you>\AppData\Local\Greenshot\ - but see your Start menu shortcut, "Open File Location" button). Find the greenshot.exe file, go to Properties, Compatibility, hit the "Change settings for all users" button at the bottom, if it's there, and then hit the "Change high DPI settings" button. Now in "High DPI settings for Greenshot.exe" dialog check first checkbox, set "I open this program", check "Override high..." and set System (Enhanced). OK all the dialogs.

Now exit Greenshot from the system tray and launch it again, either from the exe file in the folder, or from the start menu.

See if this helps?

Best regards,
SvendK

![image](https://github.com/greenshot/greenshot/assets/3720082/8285ad9f-261d-4836-9820-4f5491555154)

**Comment by DrivenDemon** [comment]
> I understand this is an old thread, but it's one of the first hits on Google for: "greenshot" dpi problems so I thought I'd help. I'm running Windows 11 Pro if that's does anything.
> 
> I'm not sure if this fixes OP's and other's problems, as I haven't read it all, but this helped my DPI problems. If I captured something on my normal resolution (QHD, 100% DPI) screen and opened in the Image Editor, it would all look fine. If I then dragged the window over to my laptop's internal monitor, a 15" 4K resolution in 225% DPI, everything would get very small. And vice versa it would be very big. This fixed it:
> 
> Go to greenshot.exe folder (e.g. C:\Users<you>\AppData\Local\Greenshot\ - but see your Start menu shortcut, "Open File Location" button). Find the greenshot.exe file, go to Properties, Compatibility, hit the "Change settings for all users" button at the bottom, if it's there, and then hit the "Change high DPI settings" button. Now in "High DPI settings for Greenshot.exe" dialog check first checkbox, set "I open this program", check "Override high..." and set System (Enhanced). OK all the dialogs.
> 
> Now exit Greenshot from the system tray and launch it again, either from the exe file in the folder, or from the start menu.
> 
> See if this helps?
> 
> Best regards, SvendK
> 
> ![image](https://private-user-images.githubusercontent.com/3720082/323630256-d586d08d-2fad-49a4-aa0f-2ffcafe3e2c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMDk1MTYsIm5iZiI6MTczMTAwOTIxNiwicGF0aCI6Ii8zNzIwMDgyLzMyMzYzMDI1Ni1kNTg2ZDA4ZC0yZmFkLTQ5YTQtYWEwZi0yZmZjYWZlM2UyYzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDdUMTk1MzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmM0MmViOGE0NmYyMTNiMzMwNGY1ZTFiOWYxZTAwNGYzODVlZjE3NTZjNjFiMTFkMjM0NjI5MjJhMGFmZGQxYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.6H7FYEF3whP-uJ7NxYF-GY4JWRb-MgQY2Cf4B6UyoFA)

This worked to fix the context menus but now when i try to grab a screen region it zooms way in..

**Comment by abacus3141-tybloko** [comment]
@SvendK Thank you very much for your recommendation re high DPI settings.  It helped me on my home computer.  I am not tech savvy, so your explanation was perfect.

The only difference was that Greenshot.exe was in program files, but I figured it out.  Thank you again!
Anna

**Comment by SvendK** [comment]
@DrivenDemon wrote 
> This worked to fix the context menus but now when i try to grab a screen region it zooms way in..

This also happened to me, not sure why. Is it still a problem after restarting your computer? If yes, you should probably create a new issue for this?

@abacus3141-tybloko Great that the info could be of help.

Also see that releases are now more frequent. There was a dead period from 2017 to May 2025 with no stable releases, but it seems this has resolved - glad to see :-) Try the last version to see if the problems still surface.

Best regards, SvendK
