### ISSUE TITLE
Feature request: Speech Bubble enchancement

### ISSUE THREAD

**Issue by Layarion** [greenshot/greenshot#26]
Would be nice if i could have a speech bubble "point" to more than one thing.

**Comment by Lakritzator** [comment]
Hmmm, interesting... something like here? https://bitstripsforschools.files.wordpress.com/2010/03/multitailspreview.png?w=500

Please do me the favor, and request this in our feature request project here:
https://greenshot.atlassian.net/

Add information which helps us to understand the request like:

- For what would this be needed? (Except for comics)
- Will you use this often?
