### ISSUE TITLE
Install option to leave out all external upload features

### ISSUE THREAD

**Issue by SquirrelAssassin** [greenshot/greenshot#260]
This GitHub repository is for developers, if you want to request a feature for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/FEATURE/issues/filter=allopenissues

**Is your feature request related to a problem? Please describe.**
dont want anything to be uploaded externally

**Describe the solution you'd like**
install option to exclude any imgur or external hosting company

**Describe alternatives you've considered**
modifying the source code but sounds annoying long and since im sure others want this ... ill request a feature

**Additional context**
non

**Comment by Lakritzator** [comment]
During the installation you can select what you want and what not.
If you want a minimistic installation, select "compact installation", if you want more control, select "custom installation".

I'd advice you to only have the office plugin, or the external command plugin (e.g. for paint)
![image](https://user-images.githubusercontent.com/708125/102404752-67b7e680-3fe8-11eb-9fcc-a06bd323c6e7.png)

**Comment by SquirrelAssassin** [comment]
Ewwwww who uses a GUI to do anything.  Gross comment.  I’ll look through the source code.

**Comment by SquirrelAssassin** [comment]
If you have some msi cmd line or exe hook to turn off the kiddie parts for Imgur that be great or a feature enhancement.
