### ISSUE TITLE
Feature Request: Trim picture automatically with a given number of pixels (from settings)

### ISSUE THREAD

**Issue by patpowerman** [greenshot/greenshot#27]
If you create a Print Screen from an entire window in Windows 10 (with Alt+PrintScreen) you always get this ugly colored 1-pixel border around every window. You have no other way then cut this border away manually.

It would be fantastic if we could choose to trim a screenshot by a given number of pixels on the left, right, top or bottom border automatically.

In the above example, I would set 1 pixel for top & bottom & left & right border and every saved picture would be exaclty as wished, borderless and ready to use in any 3rd-party program.

**Comment by Lakritzator** [comment]
Please read this: https://github.com/greenshot/greenshot/blob/develop/CONTRIBUTING.md
We have no link from our website to the github repository, this is only ment for developers.

That said, this might be the problem reported here: https://greenshot.atlassian.net/browse/BUG-1890 and fixed (??) with our most recent (untested) builds: https://github.com/greenshot/greenshot/releases

If the problem was not solved by this, please report the issue in our ticket system (JIRA).

**Comment by patpowerman** [comment]
Just to let you know, it is NOT BUG-1890.
But you are right, in the newest release the Edit -> Auto crop works as expected and cut away the 1 pixel border from a Win10 captured window.

I'm not s sure, that forcing users to create an account on your JIRA (and on every other single projects bugtracker?) is the best way to get feedback from users. This is one of the big advantages of Github?

**Comment by Lakritzator** [comment]
Github is for developers, most users don't have a github account.
Anyway we started with our JIRA system before we got on GitHub, we do not want to force our users to move to GitHub either. It's impossible to satisfy everybody, and as we do the work for free I think it's fair that we at least decide on how WE work :)

We like JIRA much better, although it's a bit slow, as it has support for different development methodologies and more.

1.2.8.12 also did something with the corners, as Windows 7 had "round" corners we had to cut these for transparent captures... now everything is square again, so the cutting made things bad. This probably prevented the autocrop, as it only works on similar colors.

About the rectangle around the window, you are correct...
I actually reported this with Microsoft, but never got an answer from them:
https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/3454610b-bac9-41dc-9da9-0ac05cc2e95d/bug-in-dwmgetwindowattribute-dwmwaextendedframebounds?forum=windowsuidevelopment

I will check this, for me the rectangle is yellowish..

**Comment by Lakritzator** [comment]
https://greenshot.atlassian.net/browse/BUG-1965

**Comment by Lakritzator** [comment]
Made a build yesterday, maybe you can have a look.
It's in the releases: 1.2.9.20

**Comment by patpowerman** [comment]
Thanks a lot for your very fast change!
The ugly border in Win10 is gone! Great! Thank you very much.
**BUT:**
In Win7 and Win10 you see now 8 points around the cursor-symbol if you open the picture directly in the Greenshot editor. This points doesn't appear if you paste the image into Word or save it as PNG or JPG or use the clipboard.

_I know that I could put the cursor outside the window .-)_

**Comment by Lakritzator** [comment]
8 points? Should be 4... you do know that you can move the cursor around in the editor after taking the screenshot? These are the "grippers" which allow you to resize the cursor...

**Comment by patpowerman** [comment]
No, I didn't know that, shame on me.
Everything OK, including the option to disable 'capture mousepointer'.
Thanks again for your help!

**Comment by Lakritzator** [comment]
Just so you know, the build is flawed... it could cause crashes when an old App is active... Just making a new build with a fix...

Please report future issues in our jira, we will get rid of the issues here as people don't read what we write :(
