### ISSUE TITLE
[Feature Request] highlight function

### ISSUE THREAD

**Issue by CharlsBags** [greenshot/greenshot#270]
Hi, I'm usig GS version 1.2.10, everything is stable and OK.

I would know if GS 1.3 will have a highlight feature like windows snipping tool.

![Immagine 2021-01-27 114825](https://user-images.githubusercontent.com/30460033/105980843-a6d06180-6095-11eb-8ed9-8ddc28137aae.png)

**Comment by Lakritzator** [comment]
This is already there, here is how.

![greenshot_highlight](https://user-images.githubusercontent.com/708125/106051833-394e2080-60e9-11eb-888a-3c1de9d5cbb2.gif)

**Comment by Lakritzator** [comment]
Closed this, as I assum this is what you wanted.
