### ISSUE TITLE
Greenshot 1.3.169 - Only DE/US/NL GUI language

### ISSUE THREAD

**Issue by bovirus** [greenshot/greenshot#271]
@Lakritzator 

You released Greenshot 1.3.169 unstable.

What's the matter did you include in the installer only DE/US/NL GUI language?
You have a lot of GUI language available.

You don't include IT language for GUI (IT language for the installer is OK) and also other languages.
Please include ALWAYS as much as possible the languages available.

**Comment by Lakritzator** [comment]
I'm not sure what you are talking about, but I needed to release so I can have some people test and close some bugs.
I didn't get to check the installer yet.

**Comment by bovirus** [comment]
@Lakritzator 

The latest version of 1.3.169 (installer) install in

\Users\xxxx\AppData\Local|GreenShot\Languages

ONLY the files

DE - language-de-DE.html and help-de-DE.tml/
EN-US - language-en-US.html / help-en-US.tml/
NL - language-nl-NL.html / help-nl-NL.tml/

In your reposioty yiou have here

https://github.com/greenshot/greenshot/tree/release/1.3/Greenshot/Languages

39 LANGUAGES
17 HELP Fiels

than why you didn't include in the latest beta of installer

39 LANGUAGES files
17 HELP files

 Please when you release a ne w beta 

- ALWAYS include ALL language/help files available in your repository.
- ALWAYS have as much as possible the same language option for the installer as for the GUI
 
This is necessary for translator to check in place installer/GUI.

Thanks.

**Comment by Lakritzator** [comment]
Due to the way that Greenshot works, it will waste a lot of resources if  all the translations are installed by default. If people want to have a certain language, I rather have that they pick it manually.

**Comment by bovirus** [comment]
Yes, but for example could be an idea that if I select Italian as istaller language by default installer script select by Italian Greenshot langauge by default for for GUI.
