### ISSUE TITLE
Print scr keyboard shortcut no longer working

### ISSUE THREAD

**Issue by GiovanH** [greenshot/greenshot#273]
My "Capture region" keyboard shortcut is set as "Print srcn", but pressing prtsc does nothing. (Alt+PrtSc and Ctrl+PrtSc for capture window and caption full screen respectively) work as expected.

**Comment by Lakritzator** [comment]
https://getgreenshot.org/faq/my-prntscreen-key-no-longer-works-with-greenshot/
