### ISSUE TITLE
Feature Request: in editor add polygon tool

### ISSUE THREAD

**Issue by aromaticfog** [greenshot/greenshot#274]

**Comment by Lakritzator** [comment]
Hi, thank you for taking the time to report this, but this is not the issue / feature tracker for our users.
This should have been clear in the templates, which I guess were broken for a period of time.

It should have said:
This GitHub repository is for developers, if you want to request a feature for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/FEATURE/issues/filter=allopenissues

I agree with the general idea, but I would like to get better specifications.
Also why do you need something like that?
Your description is really not much to go by...

I know it sounds harsh, but we have about a million users and if all report features all over the place, we cannot handle that.
Please report it at our JIRA project, with all the information you have to help us on the way.
