### ISSUE TITLE
Duplicated external commands

### ISSUE THREAD

**Issue by blackshot** [greenshot/greenshot#279]
on fresh install the latest release of 1.3 unstable after adding an external command i got them duplicated 
![imagen](https://user-images.githubusercontent.com/3688208/107666191-01a8b200-6c6d-11eb-8dc4-8ca4f69c4a5b.png)

![imagen](https://user-images.githubusercontent.com/3688208/107665952-b8586280-6c6c-11eb-87db-6dd2df981fcd.png)

**Comment by Lakritzator** [comment]
Thanks for testing out "betas", I will check this.

**Comment by badabing2005** [comment]
Actually there is one per external command defined.
![image](https://user-images.githubusercontent.com/22603312/111906312-5981c800-8a26-11eb-99c9-aaf2cdaa3a43.png)
![image](https://user-images.githubusercontent.com/22603312/111906319-60103f80-8a26-11eb-8688-b426a459305e.png)

**Comment by Lakritzator** [comment]
I had a quick look but didn't see any issues at the first glance. Can you provide your Greenshot.ini file?

You can remove all secrets, if you use any cloud services.

**Comment by Lakritzator** [comment]
Btw. what is that bottom image with all the repeated icons? Is that the editor? 😱

**Comment by badabing2005** [comment]
> 
> 
> Btw. what is that bottom image with all the repeated icons? Is that the editor? 😱

Thanks for looking into this
The bottom image?
Photoshop?

Thanks

[greenshot.zip](https://github.com/greenshot/greenshot/files/6178300/greenshot.zip)

**Comment by Lakritzator** [comment]
Thanks to your example file I managed to track it, a fix was quickly added.
Will make a newer 1.3 available with a fix in it, I guess it will be 1.3.170... just the next version **after** 1.3.157
