### ISSUE TITLE
Feature request: Add shortcut to image editor in right-click menu

### ISSUE THREAD

**Issue by rudolphos** [greenshot/greenshot#281]
Currently the only way to open image editor is to open a file through greenshot and then it gives an option to open in editor. 

Would be great if there was an option added to quickly open image editor. Greenshot image  editor is a very good alternative to MS paint (which isn't developed anymore) for quickly adding text, annotation, etc.
![image](https://user-images.githubusercontent.com/4366810/107834905-5dc02300-6da0-11eb-9811-2a8161ae77ce.png)

**Comment by Lakritzator** [comment]
Hi, thank you for taking the time to report this, but this is not the issue / feature tracker for our users.
This should have been clear in the templates, which I guess were broken for a period of time.

It should have said:
This GitHub repository is for developers, if you want to request a feature for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/FEATURE/issues/filter=allopenissues

I agree with the general idea, but I would like to get better specifications. What do you expect, e.g. if there was a button to open a new editor window, what should it show?

I know it sounds harsh, but we have about a million users and if all report features all over the place, we cannot handle that.
Please report it at our JIRA project, with all the information you have to help us on the way.
