### ISSUE TITLE
CTRL+SHIFT+C and CTRL+C not working - brand new install on win10

### ISSUE THREAD

**Issue by Chaffy-0** [greenshot/greenshot#284]
I just rebuilt my computer and after installing the latest version of Greenshot the "ctrl shift c" and "ctrl c" hotkeys aren't working to copy to the clipboard.  If I go to File -> Copy to clipboard it works fine.  Nothing under the Hotkeys section in the General tab is set to either ctrl shift c or ctrl c.  Has anyone else ran into this with 1.2.10.6?

**Comment by Lakritzator** [comment]
Hi, thank you for taking the time to report this, but this is not the issue tracker for our users.
This should have been clear in the templates, which I guess were broken for a period of time.

It should have said:
This GitHub repository is for developers, if you want to report a bug for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/BUGS/issues/filter=allopenissues

Anyway, if it would have been something easy, I would have helped.
To be honest, I don't have a clue why your hotkey are not working, maybe you have another application / tool doing something funny with the clipboard? Anyway, maybe you can have a look at that first, and if the issue remains than report the issue with more details on your Windows system on our issue tracker.

I know it sounds harsh, but we have about a million users and if all do what you do, we cannot handle that.
Please report it at our JIRA project, with all the information you have to help us on the way.
