### ISSUE TITLE
Tray icon moves to front after taking a screenshot

### ISSUE THREAD

**Issue by SomeDude77** [greenshot/greenshot#288]
If the Greenshot tray icon is hidden in the list, taking screenshots with the "capture fullscreen" hotkey makes the icon show outside the hidden tray menu, until you take another screenshot. If you only take one screenshot then the icon remains in front until you move your cursor to it. The process repeats after some times has gone and you take a screenshot again.

**Comment by Lakritzator** [comment]
I thank you for taking the time to report this, but this is not the issue tracker for our users.
This should have been clear in the templates, which you also ignored.

It should have said:
This GitHub repository is for developers, if you want to report a bug for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/BUGS/issues/filter=allopenissues


Anyway, if it would have been something easy, I would have helped.
I tried to reproduce the issue, and I see the icon appear and disappear again after the notification is gone.
It might be something with your setup, but I have no clue what this is as you didn't specify anything.

I know it sounds harsh, but we have about a million users and if all do what you do, we cannot handle that.
Please report it at our JIRA project, with all the information you have to help us on the way.
