### ISSUE TITLE
Stupid Noob question..

### ISSUE THREAD

**Issue by WilsonBradley** [greenshot/greenshot#289]
So I see the last update on Download page is 2017
I see updates here 8 hours ago. How do I get a compiled version to download?
The download is only showing source code.

Thanks.

**Comment by jklingen** [comment]
Unstable (and other) releases can be downloaded from our [version history page](https://getgreenshot.org/version-history/).

You can also find this link on our [download page](https://getgreenshot.org/downloads/), in the blue box.

Hope this helps. Let us know if you have questions.

**Comment by WilsonBradley** [comment]
Unstable Download link not working.

**Comment by WilsonBradley** [comment]
Thank you

Sincerely,

Wilson Bradley
***@***.***
▬▬▬▬▬▬▬▬▬▬▬ஜ۩☆۩ஜ▬▬▬▬▬▬▬▬▬▬
[image: 🗽]Make 𝐀𝐌𝐄𝐑𝐈𝐂𝐀 𝐆𝐑𝐄𝐀𝐓[image: 🗽]

▬▬▬▬▬▬▬▬▬▬▬ஜ۩☆۩ஜ▬▬▬▬▬▬▬▬▬▬
