### ISSUE TITLE
Text Tool Blurry When Zoomed and Exported

### ISSUE THREAD

**Issue by webluke** [greenshot/greenshot#298]
**Describe the bug**
When you zoom into an image and use the Text tool the text shows blurry or pixilated, this does not represent the final save of the image. When zoomed to 100% the text seems to look as it should. Zooming out to 75%, the textbox and text behave as tho they lost their location and the text moves. When you save the image the text is blurry similar to what was shown by the zoomed-in view.

**To Reproduce**
1. Open an image in the editor or take a screenshot.
2. Zoom to 200%
3. Add a text box and enter some text, end the edit text input 
4. The text will be blurry
5. Zoom to 100% 
6. The text will look as it should
7. Zoom to 75%
8. The text moves and the text box boundary has stayed the same size
9. Save the image to disk
10. Preview image to see the text is blurry like the zoomed preview

**Expected behavior**
When putting text the final text after closing the edit text field should match the final rendering of the pixels no matter the zoom level. The text should not move based on zoom level. Text exported should not change from editor to png/file.

**Screenshots**
Zoomed in 200% with text blurry
![image](https://user-images.githubusercontent.com/5162188/112182713-258fd980-8bc3-11eb-8cbc-34688e085f5f.png)
Zoomed out 100% text looking normal
![image](https://user-images.githubusercontent.com/5162188/112182765-33455f00-8bc3-11eb-9422-0452de656775.png)
Exported image with blurry text.
![image](https://user-images.githubusercontent.com/5162188/112183009-6c7dcf00-8bc3-11eb-8d13-57a85131fa33.png)

**Versions (please complete the following information):**
 - 1.3.173 and 1.3.172 observed, 1.3.139 I had before did not have this bug
 - Windows 10 20H2

**Additional context**
This is one of a few text-related bugs I have found with this newer build. The other was related to Number Dots text not centered in the dot. The other was when resizing textboxes and shape boxes if you resize from one grip to another you lose the first grip and are now clicked on the second grip.

**Comment by Lakritzator** [comment]
I changed the drawing code to use TextRenderer.DrawText instead of previously graphics.DrawString.
The reason for this was that graphics.DrawString had issues with emoticons, and this is supposedly solved with TextRenderer.
It seems there are a lot of downsides, I hope it's just something in the settings for the DrawText.

**Comment by Lakritzator** [comment]
It doesn't look good for TextRenderer.DrawText, it might draw unicode (emoticons etc) much better than graphics.DrawString, but it's making me crazy. There is no anti-aliasing, and it causes issues with cleartype... I might need to rollback the fix for the emoticons to fix this.

**Comment by Lakritzator** [comment]
I had to rollback the changes for #283, they caused this.

https://twitter.com/lakritzator/status/1378418833455775752?s=20

In the next build things should work again.

**Comment by Lakritzator** [comment]
Published unstable 1.3.194
