### ISSUE TITLE
Resize Tool Allows User to Enter Text into Unit Select Drop Down

### ISSUE THREAD

**Issue by webluke** [greenshot/greenshot#303]
**Describe the bug**
When editing images and you use the resize tool, the user can change the unit text to whatever they want. If they change the text they can't press ok to finish the resize.

**To Reproduce**
Example steps to reproduce the behavior:
1. Capture Screen
2. Open Editor
3. Select Resize Tool
4. Click Into Unite Size Text (Pixel or Percent)
5. Edit the Text
6. Can't Press OK With Invalid Units

**Expected behavior**
When users click or tab into the unit Combobox it should only allow selection not edit. Changing the DropDownStyle to DropDownList to lock the text.

**Screenshots**
![image](https://user-images.githubusercontent.com/5162188/112886812-a3565800-908f-11eb-9e3f-48b42a757c85.png)
![image](https://user-images.githubusercontent.com/5162188/112889171-8a02db00-9092-11eb-902b-c714a56132a7.png)

**Versions (please complete the following information):**
 - Greenshot version 1.3.178 and below
 - Windows version 20H2 (19042.906)

**Additional context**
None

**Comment by Lakritzator** [comment]
Interesting catch, thanks for pointing this out!

**Comment by Lakritzator** [comment]
Fixed in 1.3.194
