### ISSUE TITLE
Drop shadow on text is always applied

### ISSUE THREAD

**Issue by badabing2005** [greenshot/greenshot#305]
Using the latest release as of this writing
Greenshot 1.3.178
Even though I am not selecting drop shadow, drop shadow is always applied on Text

![image](https://user-images.githubusercontent.com/22603312/113480292-9c4d9200-9461-11eb-8531-fe19b9023213.png)

**Comment by Lakritzator** [comment]
This is a side effect of moving towards a different rendering to fix #283, but the change went sideways.
https://twitter.com/lakritzator/status/1378418833455775752?s=20

I just rolled back the change für #283, in the next build this is solved.

**Comment by Lakritzator** [comment]
Published unstable 1.3.194 where this is fixed (rolled back #283)

**Comment by badabing2005** [comment]
Thanks for a quick resolution, it works correctly now.
Much appreciated.

![image](https://user-images.githubusercontent.com/22603312/113512689-c8d1de80-9533-11eb-8365-c31e5c210206.png)
