### ISSUE TITLE
Support "Capture Region" on Tray icon left click

### ISSUE THREAD

**Issue by gustavotrott** [greenshot/greenshot#314]
In `%APPDATA%\Greenshot\Greenshot.ini` there is the option `LeftClickAction`
And I see that the options are:
```
    public enum ClickActions {
        DO_NOTHING,
        OPEN_LAST_IN_EXPLORER,
        OPEN_LAST_IN_EDITOR,
        OPEN_SETTINGS,
        SHOW_CONTEXT_MENU
    }
```

It would be great if we have the option `CAPTURE_REGION`. 
This is the option that I use more often and would be very practical to capture region without need to open Context Menu first or use the keyboard.

Thank you!

**Comment by Lakritzator** [comment]
I've added the following, over the usefulness we can discuss:

```
        CAPTURE_REGION
        CAPTURE_SCREEN
        CAPTURE_CLIPBOARD
        CAPTURE_WINDOW
        OPEN_EMPTY_EDITOR
```

So, these can ONLY be added by using an editor with the greenshot.ini, the OPEN_EMPTY_EDITOR is a request that I've got, but doesn't make a lot of sense yet... you can't change the background in the editor, so it's very limited.

I'll inform you of the build where this can be tested.

**Comment by Lakritzator** [comment]
Available in 1.3.201 or later which can be found here https://github.com/greenshot/greenshot/releases

**Comment by gustavotrott** [comment]
Awesome! I just downloaded the last version and seems to be working great!
Thank you @Lakritzator!

Maybe you should consider include this option in the interface.
For me it is not necessary, but it is a very useful option that most of the users will never know the existence.

**Comment by Lakritzator** [comment]
It's currently EXTREMELY hard to get something into the interface.
This has to do with our limited translation process, and also the little real-estate (place) the UI offers.
We do not like to complicate things right now, so we decided to not extend the UI in 1.3
For 2.0 we made a new UI, but the 2.0 branch is state due to other issues with .NET, so we will need to revise.

Long story short: Currently not adding this to the UI

**Comment by Lakritzator** [comment]
Closing this issue, it's in the 1.3 code base and we will see how we go forward with the UI another time.

**Comment by tripper311** [comment]
Totally wanting this too but I didn't get it working.  I opened this file `%APPDATA%\Greenshot\Greenshot.ini`

Found the `LeftClickAction=SHOW_CONTEXT_MENU` and updated it to `LeftClickAction=CAPTURE_REGION`

Then I saved it, re-opened the app and it doesn't work.  Anything else I'm supposed to do?
