### ISSUE TITLE
Greenshot 1.3 Windows 10 Plugin - OCR does not work if the captured region around the text is small

### ISSUE THREAD

**Issue by slowfox69** [greenshot/greenshot#315]
**Describe the bug**
OCR does not work, if the captured region around the text is rather small

**To Reproduce**
Example steps to reproduce the behavior:
- Open Notepad, enter some blank lines and then write some text, e.g. "The quick brown fox jumps over the lazy dog"
- Set the Font in Notepad e.g. to Consolas Regular 11 points (checked on a Notebook with 1600x900 screen resolution)
- Now capture a screenshot from this text using rather small margins around the text, just that the complete text is included in  
  captured region, e.g. in my case 355x21 points 
- The screenshot opens in Greenshot editor, now apply the Windows 10 OCR pressing the appropriate button in the toolbar
- Open another instance of Notepad and try to paste the OCR result --> the paste button is disabled, the clipboard does not contain any OCR text result.
- Now repeat the capturing, but this time use a wider area around the captured text, so now the captured region around the text was in my case 378x53 points.
- Again Greenshot editor opens, apply again the Windows 10 OCR
- Now paste again the OCR result in the 2nd instance of Notepad. Now the OCR text is recognized correctly
- Even with smaller fonts using in Notepad (Tested with Consolas Regular, 9 point) OCR works correctly, if the captured region is large enough, but we do not get any results, if the margin around the captured text is very small

**Expected behavior**
OCR should also work, if the captured region around a single line text is small and 
OCR should also work, if the font of the captured text is small (9 points or smaller)

- I compared the results with Text-Grab (https://github.com/TheJoeFin/Text-Grab), which also uses the Windows 10 OCR and here it works better, even with a very small margin around the captured text using their "Fullscreen" mode. I checked then the code (see https://github.com/TheJoeFin/Text-Grab/blob/master/Text-Grab/Utilities/ImageMethods.cs, line 153 and the trick seems to be that the captured image is enlarged (with factor 1.5) before applying the OCR

**Screenshots**
N/A.

**Versions (please complete the following information):**
 - Greenshot version: Using Greenshot-INSTALLER-1.3.194-UNSTABLE.exe (03 Apr 2021) from GetScreenshot.org
 - Windows version: Windows 10 20H2 OS Build 19042.928 Enterprise version
 - Screen resolution 1600x900

**Additional context**

Thank you.

**Comment by Lakritzator** [comment]
Good point, for 1.2 where we used a different technology, we bypassed that issue by growing the "canvas". Somehow I forgot to implement that for 1.3, but that should not be a big deal.

Thanks for reporting this!

**Comment by slowfox69** [comment]
Thank you for looking into that issue.

**Comment by Lakritzator** [comment]
Please test with https://github.com/greenshot/greenshot/releases/tag/v1.3.201 or newer

**Comment by slowfox69** [comment]
Thank you very much. I downloaded the 1.3.201 release and checked it on 2 different machines, the original one using a screen resolution 1600x900 and another one using UHD display with 3840x2160. Again I used a very tiny border around the selected text and the ocr was working properly. Thank you very much for solving this issue.

**Comment by Lakritzator** [comment]
Thanks for reporting, and the feedback!
