### ISSUE TITLE
Region capture will not paste without clearing Win10 notification.

### ISSUE THREAD

**Issue by DontTrustMyCode0** [greenshot/greenshot#325]
**Describe the bug**
When taking region screenshots in Windows 10, the clipboard will not always off-load the last screenshot taken until the notification is cleared from the Windows 10 notification center

**To Reproduce**
Example steps to reproduce the behavior:
1. Capture region (My hotkey is Ctrl + Alt + Prtsc)
2. Copy to clipboard
3. Attempt to paste into Photoshop CC (version doesn't matter, this has been happening for months on various versions and apps)
4. Repeat until the new screenshot is no longer pasting
5. Clear the capture notification from Windows 10 Notification Center
6. Attempt to re-paste
7. The new screenshot will now paste

**Expected behavior**
The new screenshot should always paste without clearing the notification

**Versions (please complete the following information):**
 - Greenshot version: 1.2.10 Build 6 64-bit
 - Windows version: 19043.1110

**Additional context**
Repeatable on other versions of Win10 and Greenshot

**Comment by Lakritzator** [comment]
Do you have a chance to test this behavior with one of our most recent builds?
https://github.com/greenshot/greenshot/releases/tag/v1.3.211

As we changed so much, before I work on this I need to know if this hasn't been solved yet.

**Comment by Lakritzator** [comment]
Whenever you have time to look at the most recent builds found here: [https://github.com/greenshot/greenshot/releases](https://github.com/greenshot/greenshot/releases/tag/v1.3.211)
Let us know the result, if the issue still exists.

Until then, this issue is closed due to time out.
