### ISSUE TITLE
element in editor got lost

### ISSUE THREAD

**Issue by mischlrebl** [greenshot/greenshot#337]
when working with a screenshot in the editor, I often add other screenshots into the image.

but from time to time, a whole sub-image is not there anymore, only the handles in the corner and the midpoints are visible, but not the image itself.
logically, no undo would help nor is any interesting visible in the log.

any idea how to even chase this bug so an expert could investigate along an audit trail? thx

**Comment by Lakritzator** [comment]
I do not see any way of using an audit trail to fix this, we need to track the issue by trying to reproduce it.

Can you give more information about your setup (windows & greenshot versions)?
Can you give more information on what you do, and when this seems to happen?
(e.g. after doing nothing, or when doing undo/redo, or moving stuff, or changing to another editor instance)

If you see it a lot, can you please try this with Greenshot 1.3, find it in the releases of this repository.

**Comment by Lakritzator** [comment]
Closing this issue as I cannot help without feedback.
