### ISSUE TITLE
add cryptodonate button

### ISSUE THREAD

**Issue by dzmitry-lahoda** [greenshot/greenshot#350]
solana/ada just not to pay tooo much fees. will donate 25 USD

**Comment by Lakritzator** [comment]
I just wanted to say, that it's really sweet of you to want to donate, but we currently do not do crypto currency, as it will cost us more work, and we already have more than enough with Greenshot on it's own. I would find it sad, if someone pays $25 in crypto, and we do not have time to collect it, and the currency drops in value.

We might consider another time, but short term it's not on our out like of TODOs.

We have a couple of ways you can donate us, some aren't even on our website yet, these are:

- PayPal (on our site)
- Bank transfer (on our site, this might be without fees)
- Amazon (on our site, but only for Germany)
- GitHub sponsors (only on our GitHub Repository visible)
- Open collective (only on our GitHub Repository visible)
  - They support credit card

If that is not to your liking, I would suggest you buy yourself a nice coffee / tea with something good. And have a feel-good day 😉
