### ISSUE TITLE
OCR Image to Text

### ISSUE THREAD

**Issue by relipse** [greenshot/greenshot#353]
This GitHub repository is for developers, if you want to request a feature for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/FEATURE/issues/filter=allopenissues

**Is your feature request related to a problem? Please describe.**
It would be nice to copy a portion of the screen and OCR it to text.

**Comment by Lakritzator** [comment]
For Greenshot 1.2 this is already in there but uses very old tech: https://getgreenshot.org/faq/how-can-i-use-greenshot-for-ocr/
For Greenshot 1.3, still pending to be released, this is available if you have Windows 10, build 17763 or later.

The feature is very basic, you can select OCR as a destination for your capture, and it "just" copies the found text into the clipboard. I would advice you to have a go with 1.3 "beta", which can be found here: https://github.com/greenshot/greenshot/releases

Although I still have plans to continue on the OCR functionality, have some nice features planed, but for now I will close this, as we already have what you requested.
