### ISSUE TITLE
Blinking windows

### ISSUE THREAD

**Issue by sylvaindd** [greenshot/greenshot#365]
**Describe the bug**
After doing a screenshot with Greenshot (region, full screen or window), all my windows start blinking (every second or so), so is the taskbar, the focus is constantly lost.
As soon as I copy something else (like text), the problem stops.
I am able to paste the screenshot just fine.

**To Reproduce**
Example steps to reproduce the behavior:
1. Capture 

**Expected behavior**
No blinking

**Versions (please complete the following information):**
 - Greenshot 1.2.10.6 and  1.3.220
 - Windows 11 21H2 22000.469

**Additional context**
I am thinking this is due to to the latest Windows 11 Update, I didn't have this issue before.

**Comment by Lakritzator** [comment]
This is a known issue, actually with Windows 11 and not just with Greenshot, I advice you to read and subscribe to #348

Actually the capture process itself most likely doesn't trigger this bug, but the fact that it's copied to the clipboard.

Closing this as a duplicate.

**Comment by sylvaindd** [comment]
Didn't see that issue, thank you
