### ISSUE TITLE
Multi Monitor does not work

### ISSUE THREAD

**Issue by dingolino** [greenshot/greenshot#367]
Hi,

I came from 1.3.220 and installed the new
1.3.229 and 1.3.231 Version.

I am running win 10 on a laptop in a dockin g station with 3 screens in total.

With the 2 new Versions the capture is completly "messed" up. I am trying to capture something on screen 1 and the capture window is poping up on screen 3 and everything is "shifted" and "magnified".

I tried a restart after installation but this does not help.

Going back to Version 1.3.220 was working for me.

Best regards

Edition	Windows 10 Pro
Version	21H1
Installiert am	‎22.‎12.‎2020
Betriebssystembuild	19043.1503
Leistung	Windows Feature Experience Pack 120.2212.4170.0

This GitHub repository is for developers, if you want to report a bug for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/BUGS/issues/filter=allopenissues

**Describe the bug**

**To Reproduce**
Example steps to reproduce the behavior:
1. Capture '....'
2. Open Editor
3. Add a line
4. Resize

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Greenshot version
 - Windows version

**Additional context**

**Comment by Lakritzator** [comment]
I'll check this, although it surprises me a lot. Thanks for mentioning with what version it does work.

**Comment by Lakritzator** [comment]
I actually cannot reproduce this yet, while I will try on a different setup with multi monitors later, I do have a question.

Do you use slack, PowerToys or DisplayFusion? Or any other tools which manage the sizes and locations of your windows?

**Comment by dingolino** [comment]
Hi Robin,




I am using




https://www.actualtools.com/windowmanager/







since several years now. Not the programs you mentioned.




Best regards,




Claus







Am 29.01.2022 um 17:12 schrieb Robin Krom ***@***.***>:



I actually cannot reproduce this yet, while I will try on a different setup
with multi monitors later, I do have a question.

Do you use slack, PowerToys or DisplayFusion? Or any other tools which manage
the sizes and locations of your windows?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by Lakritzator** [comment]
Oh, thanks for the quick feedback.
We had to add a hack, as the application Slack resizes the Greenshot region capture window. The hack here, is that if some application resizes the window, Greenshot resizes it back again.

Did you have to tell the app somehow to exclude Greenshot from it's management?

If possible, can you get a screenshot of the behavior?

**Comment by dingolino** [comment]
Let me see what I can do.




Maybe I make a foto.




I will install the latest version and than I will make a try also with a
deactivated "Actual Window"




Best regards,




Claus




Am 29.01.2022 um 17:29 schrieb Robin Krom ***@***.***>:



Oh, thanks for the quick feedback.
We had to add a hack, as the application Slack resizes the Greenshot region
capture window. The hack here, is that if some application resizes the window,
Greenshot resizes it back again.

Did you have to tell the app somehow to exclude Greenshot from it's
management?

If possible, can you get a screenshot of the behavior?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by dingolino** [comment]
Please find enclosed the fotos of my Screens.




It is making no difference whether I deactivate Actual Manager or whether it
is active.




Display 1.1 means this is Screen No 1 before activating greenshot




Display 3.2 means therefore Screen No 3 after activating greenshot




And screen No 3 is making the trouble







Screen resolutions:




Display 1 1920 x 1080

Display 2 2560 x 1440

Display 3 1600 x 1200




Display 3 is a old one, this resolution is not common today,  but it is still
working.




best regards,




Claus














Am 29.01.2022 um 17:29 schrieb Robin Krom ***@***.***>:



Oh, thanks for the quick feedback.
We had to add a hack, as the application Slack resizes the Greenshot region
capture window. The hack here, is that if some application resizes the window,
Greenshot resizes it back again.

Did you have to tell the app somehow to exclude Greenshot from it's
management?

If possible, can you get a screenshot of the behavior?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by Lakritzator** [comment]
Leider hat es mit die Anhänge nicht geklappt, kannst du die bitte direkt an dem Issue dranhängen?

**Comment by dingolino** [comment]
Probiere es mal mit dem dropbox link







https://www.dropbox.com/sh/otnxwihxl2i24b8/AACzUGt6Gi_oALKAdl_CUCmca?dl=0







Ich hatte die email 2mal geschickt und die Bilder verkleinert.




Bei Display 3 ist das Problem.




Hast Du die email mit den Infos bekommen?







Viele Grüße




Claus




Am 29.01.2022 um 22:45 schrieb Robin Krom ***@***.***>:



Leider hat es mit die Anhänge nicht geklappt, kannst du die bitte direkt an
dem Issue dranhängen?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by dingolino** [comment]
Anbei nochmal die alte email




Grüße




Claus












Please find enclosed the fotos of my Screens.




It is making no difference whether I deactivate Actual Manager or whether it
is active.




Display 1.1 means this is Screen No 1 before activating greenshot




Display 3.2 means therefore Screen No 3 after activating greenshot




And screen No 3 is making the trouble







Screen resolutions:




Display 1 1920 x 1080

Display 2 2560 x 1440

Display 3 1600 x 1200




Display 3 is a old one, this resolution is not common today,  but it is still
working.




best regards,




Claus









Am 29.01.2022 um 22:45 schrieb Robin Krom ***@***.***>:



Leider hat es mit die Anhänge nicht geklappt, kannst du die bitte direkt an
dem Issue dranhängen?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by bitsky6** [comment]
Hello,

So I think I have the same issue.

Windows 11 (22000.469)
Greenshot 1.3.231

What happens is what i read above.

I have a 3 Monitor Setup.

Monitor 1: Portrait FullHD (Extended)
Monitor 2 : Landscape 4K (Main Monitor)
Monitor 3 : Landscape FullHD (Extended)

<img width="496" alt="image" src="https://user-images.githubusercontent.com/57507315/151760130-cec3c503-d61d-4d14-9d68-e1ebe47f901e.png">


If Monitor 2 is set to Main Display as I always use the Monitor 1 Desktop Shifts to the Right on Monitor 2 and a part of Monitor 2 on Monitor 3.

The Crosshair of Greenshot where it magnified is not in the right position.

Can't capture anymore Monitor 1 either.

**If Monitor 1 is set as Main Monitor then it works correctly on all 3.**

The issue is if It is not the 1st Monitor as Main Monitor it will Shoft all Screens out of position.

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/57507315/151761000-1240f521-9df0-48ce-a80c-06a45df1040e.png">

**Comment by Lakritzator** [comment]
@bitsky6 I see what you mean, but I cannot reproduce it. 
I tried to reproduce it with 1.3.231 with 3 displays, from left to right: "1" internal on my laptop on 150%, "3" external on 100% which is my main display, and "2" also on 100%. Changing the main display also didn't change anything on the Greenshot behavior.

Did it work with older versions?

**Comment by bitsky6** [comment]
Hello @Lakritzator,

So it was working well until 1.3.229.

I Updated and after that it happened. Even if I went back to 1.3.229 the problem remained the same.

For me Monitor 1 is 100% Monitor 2 is 150% and Monitor 3 100%

Here is the log when i try to capture.

<img width="984" alt="image" src="https://user-images.githubusercontent.com/57507315/151771382-8ee86faf-b0c6-404c-bd32-bf0a6bc61237.png">

**Comment by Lakritzator** [comment]
@bitsky6 are you by any chance using Slack? (there is a know issue, it's behaving badly towards Greenshot)
Thanks for adding the logs, here we can see that something is resizing Greenshot to "198x56" although it should be "6840x2160" and Greenshot is competing against it. I guess I only set the dimension, not the location, if so I **might** be able to fix it, but the question stays "what the f*ck is changing Greenshot". If not slack, are you running anything else?

**Comment by bitsky6** [comment]
Hello,

I am not using Slack or anything particular that could think of since the update.

Thanks

**Comment by Lakritzator** [comment]
Forget my previous comment, I actually see the same logs as you have, I will revert the slack change back, to see if it is the cause thus solves the issue.

**Comment by bitsky6** [comment]
Just for info, somehow the problem is can't find the Monitor allignment.

If I have a Monitor on the Left side will not be visible and will just push it to the Right.

For example if I add them in this order it works.

<img width="785" alt="image" src="https://user-images.githubusercontent.com/57507315/151778785-1d5facd8-cd6f-4f89-a8a0-2bce69b32031.png">

If I add both to the Left Both screens get pushed to right and cant take screenshot on them.

<img width="761" alt="image" src="https://user-images.githubusercontent.com/57507315/151779326-c5b4f639-74a0-4eba-a16e-82089b07b1a4.png">

If I add it to vertical position it still works as intended, only everything to the left from the main monitor will not work.

<img width="764" alt="image" src="https://user-images.githubusercontent.com/57507315/151779552-f7654ef7-f479-474a-ad0e-a4bde34e88b3.png">

**Comment by olf** [comment]
I also faced this issue last week when I tried to update from build 220 to a newer one and had to go back to 220.

I have a 2 monitor setup (laptop internal + external high DPI display) with Windows 10 (21H1 build 19043.1466). I'm not using Slack.

**Comment by bitsky6** [comment]
@olf - Don't have that version anymore on github to download.

**Comment by bitsky6** [comment]
Good I just found the 220 installer in my Downloads folder as on Github not available anymore.

I can confirm that it happens after version 220.

With 220 works correctly.

Thanks

**Comment by Lakritzator** [comment]
Please have a go with 1.3.234 (or anything newer if you read this later): https://github.com/greenshot/greenshot/releases

**Comment by bitsky6** [comment]
Thank You, problem fixed in latest.

**Comment by Lakritzator** [comment]
@dingolino Can you confirm?

**Comment by Lakritzator** [comment]
FYI: I changed the code in such a way that in theory the fix for the Slack issue, which triggered this, is still in place. I noticed that it might have been less than optimal, so I changed it a bit.

**Comment by olf** [comment]
Build 234 works for me, too. Thanks a lot for the fix!

**Comment by landeeno** [comment]
Hi there, 
I stumbled upon this thread while trying to figure out why I am having similar issues to those described above. Essentially, with the current release version, the capture region works great if my cursor is on the primary monitor; however, whenever I try and take a screenshot when the cursor is on the secondary monitor, the capture region defaults to a zoomed-in version of whatever is currently being displayed on the primary monitor. I am using both Slack and PowerToys FancyZones (which could be the issue). 

I would like to try using build 1.3.234; however, I am not sure how to install this build on my computer as there is no executable installer available (that I know of). I have located the source code on the GitHub file but do not know how to install. Could someone please assist?

Thanks in advance, 
Landon

**Comment by bitsky6** [comment]
https://github.com/greenshot/greenshot/releases/tag/v1.3.270

Best Regards / Mit freundlichen Grüßen,
----------------------------------------------------------------------
László Pető
System Administrator / Network Engineer
Broadcasting Specialist
IT & AV Specialist
----------------------------------------------------------------------
Xcontrol - Digital Experience Innovators
Mönckebergstraße 13, 20095 Hamburg
Web: www.xcontrol.de
----------------------------------------------------------------------
________________________________

**Comment by landeeno** [comment]
Found an executable at the bottom and it's working great! Thank you!

**Comment by praschl** [comment]
Thank you, v1.3.270 fixed it for me!
