### ISSUE TITLE
FR: blur area filter

### ISSUE THREAD

**Issue by daxliniere** [greenshot/greenshot#368]
Title says it all.
In the the image editor, it would be great to have a filter that allows us to blur an area of an image.

**Comment by Lakritzator** [comment]
This is already available in Greenshot 1.2, look at the obfuscator tool! You can change the filter for it, there is pixelate and blur.
https://getgreenshot.org/help/#editor-obfuscate

<img width="167" alt="image" src="https://user-images.githubusercontent.com/708125/151667877-7cb2ecfb-3c59-4686-a185-474378cad3cf.png">

**Comment by daxliniere** [comment]
Awesome, thank you so much Robin! :)
