### ISSUE TITLE
FR: Zoom in/out for image editor

### ISSUE THREAD

**Issue by daxliniere** [greenshot/greenshot#369]
Title says it all.
Adding zoom in/out funcitonality to the image editor would be a great asset. Most editors support **CTRL +/-** and **CTRL+mousewheel** for this, though many also have zoom in/out buttons in the bottom right corner of the interface.

I'd really love to see this feature added to Greenshot Image Editor.

All the best,
Dax Liniere.

**Comment by Lakritzator** [comment]
Hi, this is already added in the 1.3, check out our pre-releases: https://github.com/greenshot/greenshot/releases

**Comment by daxliniere** [comment]
Great, thank you again, Robin. I'll check that out and report if I run into any problems.

Cheers!
Dax.
