### ISSUE TITLE
Being able to choose the number of digits for ${NUM} Filename pattern

### ISSUE THREAD

**Issue by jupiter104** [greenshot/greenshot#376]
**Describe the bug**
If you use **${NUM}** as the **Filename pattern** it automatically outputs an incrementing 6 digit number but what if you want an incrementing 4 digit number or a 7 digit number?

**To Reproduce**
Example steps to reproduce the behavior:
1. In the **Output** tab, make sure your **Filename pattern** is **${NUM}** 
2. In the **Destination** tab, make sure you have checked **Save directly**
3. Take multiple screenshots.
4. You will see the file names of the screenshots are six digit numbers.

**Expected behavior**
It would be better if Greenshot had a filename pattern option to choose the number of digits. For example, ${NUM3} would output incrementing 3 digit numbers starting from 001, then 002 and so on. {$NUM7} would output 7 digit numbers starting from 0000001.

**Versions (please complete the following information):**
 - Greenshot 1.2.10 Build 6 (64 Bit)
 - Windows 10 Pro (Version: 21H2, OS Build: 19044.1503)

**Additional context**
I've also noticed if you use ${title} as the filename pattern, it can output very long filenames if the title of the window was very long. It would be better if we could limit the number of characters like ${title10} which would only use the first 10 characters to name the screenshot file.

**Comment by Lakritzator** [comment]
We've got you covered, wait for my answer later... can't write right now, maybe in ~12 hours.

**Comment by Lakritzator** [comment]
So, for the formatting you have the following options:

`${x:yz}` where:


1.  "x" the placeholder, we support
  - domain
  - user
  - hostname
  - YYYY - current year
  - MM - current month
  - DD - current day
  - hh - current hour
  - mm - current minutes
  - ss - current seconds
  - now - datetime of now
  - capturetime - time of the capture
  - NUM - incrementing number
  - title - title of the window which was captured
  - MyPictures - special folder for your pictures
  - MyMusic - special folder for your music (don't ask...)
  - MyDocuments - special folder for your documents
  - Personal - special folder for your personal files
  - ApplicationData - special folder for your application data (roaming)
  - Desktop - special folder for your desktop
  - LocalApplicationData - special folder for your local application data
 
2. y is the formatter, and z the parameters for that formatter we accept
 - p for padding, with width,padchar (e.g. ${NUM:p10,0} for a 10 digit NUM with padding 0s)
 - r for replace, with oldstring,newstring (e.g. ${title:rInternet Explorer,} to replace "Internet Explorer" in the title with an empty string
 - d for date formatter with dateformat e.g. ${now:"YYYY-MM-DD"} possible formats can be found [here](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings)
 - s for substring with start,end e.g. ${title:s0,10} there are negative start values to start from the end

(Sorry there seems to be an issue with the formatting, I will update this at another time, but the message should be clear?)

**Comment by jupiter104** [comment]
Yeah that makes sense. Really awesome program you've created. The built-in windows snip and sketch is such garbage. And most other programs out there are so bloated and slow.
