### ISSUE TITLE
Preferences window is too small

### ISSUE THREAD

**Issue by Mr-Update** [greenshot/greenshot#379]
This GitHub repository is for developers, if you want to report a bug for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/BUGS/issues/filter=allopenissues

**Describe the bug**
Since version 1.3.229 up to and including version 1.3.239, the preferences window is too small: 340 x 406 pixel.

**To Reproduce**
Open 'Preferences...'

**Expected behavior**
Until version 1.3.220 it was 453 x 463 pixel in size.

**Screenshots**
Version 1.3.229 - 1.3.239
![Einstellungen_239](https://user-images.githubusercontent.com/37781396/153729353-690ae4ce-5603-45df-ae30-b49a3ace2bef.png)

Version 1.3.220
![Einstellungen_220](https://user-images.githubusercontent.com/37781396/153729350-d6b4dbfd-00e9-4f6d-a1ad-a21944e8ff57.png)

**Versions**
 - Greenshot 1.3.229 - 1.3.239
 - Windows 10 21H2

**Comment by Lakritzator** [comment]
Thanks for reporting this, I changed something for better DPI behavior and maybe I overlooked something.
I actually noticed it and wanted to report it myself, so I don't forget forget it.

**Comment by Lakritzator** [comment]
Can you have a look at v1.3.244 or later, found here: https://github.com/greenshot/greenshot/releases 
I think it's much better now, let me know.
