### ISSUE TITLE
BUG-2901, More Information about context Windows 11 Pro Utvärderingsversion

### ISSUE THREAD

**Issue by ArneHoder** [greenshot/greenshot#386]
This GitHub repository is for developers, if you want to report a bug for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/BUGS/issues/filter=allopenissues

**Describe the bug**
BUG-2901, Error message on start of windows. Null reference

**To Reproduce**
Example steps to reproduce the behavior:
1. Close Windows
2. Start Windows

**Expected behavior**
Error message with System.NullReferenceException stack dump in ImgurlPlugin.

**Screenshots**
Windows version.
![2022-02-23 02_11_07-WindowsVersion](https://user-images.githubusercontent.com/83922934/155246374-b4f91051-66dc-41e6-80b8-70ee7feac2fe.png)

Greenshot about with version. (Greenshot started without problems after closing error message. Screenshots taken with it.)
![2022-02-23 02_13_13-GrenshotAbout](https://user-images.githubusercontent.com/83922934/155246614-b5a07f80-970d-44b5-8c66-172998c84062.png)

**Versions (please complete the following information):**
 - Greenshot version 
 Software version: 1.2.10.6-RELEASE-c2414cf0149a1475ea00520effc01b40087c225c (64 bit)
.NET runtime version: 4.0.30319.42000+
 - Windows versionen 
 Windows 11 Pro Utvärderingsversion.Build 22557.ni_release.220210-1445.
Windows version from Insider program.

**Additional context**

More info about BUG-2901.
Software version: 1.2.10.6-RELEASE-c2414cf0149a1475ea00520effc01b40087c225c (64 bit)
.NET runtime version: 4.0.30319.42000+
Time: 2022-02-22 23:39:06 +01:00
OS: unknown   (x64)  10.0 build 22557 revision 0
GDI object count: 30
User object count: 21

Exception: System.NullReferenceException
Message: Objektreferensen har inte angetts till en instans av ett objekt.

Stack:
   vid GreenshotImgurPlugin.ImgurPlugin.<UpdateHistoryMenuItem>b__13_0()
   vid System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   vid System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   vid System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   vid System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   vid System.Windows.Forms.Control.InvokeMarshaledCallbacks()

Configuration dump:
Windows 11 Pro Utvärderingsversion.Build 22557.ni_release.220210-1445.
Windows version from Insider program.
Found error message with link here on start up of Windows.

/ Best Regards
A very happy user of Greenshot and a system developer.
peter.engelbrektsson@hotmail.com
peter@midgardskultur.se

https://greenshot.atlassian.net/browse/BUG-2901

**Comment by Lakritzator** [comment]
This is already fixed in 1.3, you either can try the pre-releases from the releases in this repo or wait for it. (no release date set yet)
