### ISSUE TITLE
Open editors as closed submenu

### ISSUE THREAD

**Issue by omidnik8** [greenshot/greenshot#390]
when you want to use Open in editor option , a pop up list of other open editors , obscure the option , and therefore , it results to drop the captured screen in an unwanted editor 

would be great if we could have the list of open editors as a closed sub-menu , so it wouldn't get in the way.
thanks
![GreenShot_openEditors](https://user-images.githubusercontent.com/101666602/158448699-9b39d31a-5bfd-4914-86ad-209cf2980d14.jpg)

**Comment by Lakritzator** [comment]
They come if you hoover on them, giving you the option to click on the item itself to open another editor.
To me this seems more likely to be a bug, as the title it displays is WAY to long, it should be cut off.

**Comment by Lakritzator** [comment]
I will provide a build later this week where this fix is in, so you can have a look if this mainly solves your issue.

**Comment by Lakritzator** [comment]
Test can be done with v1.3.244 or later, found here: https://github.com/greenshot/greenshot/releases
