### ISSUE TITLE
couldn't find clipboard image v1.3.246 

### ISSUE THREAD

**Issue by snowdej** [greenshot/greenshot#396]
how to reproduce

Look at the right click taskbar context menu
"open image from clipboard" alt-ctrl-shift-p  is greyed out (nothing in clipboard)

When the capture prefs ..... 
"open in image editor" unticked
"copy to clipboard"  IS ticked

Take a screenshot

Look at the right click taskbar context menu AGAIN
"open image from clipboard" alt-ctrl-shift-p  is  NO LONGER greyed out (clipboard has an image)

Press open from clipboard alt-ctrl-shift-p

Popup error
![image](https://user-images.githubusercontent.com/660851/160399862-0627c993-fe2a-499a-8399-22a0fd9fd7f7.png)

Previous version works 1.3.239

If you open straight to  image editor it works as before and as expected

expected behaviour to open the clipboard image

windows version Version	10.0.19044 Build 19044

**Comment by Lakritzator** [comment]
I cannot reproduce this, what are your current clipboard formats? See in the expert settings.

**Comment by snowdej** [comment]
PNG format and "device independent bitmap" are ticked

I re-installed the prior version over the top to get back the functionality - but I can re-install .246 if you want to know more

I know the capture has worked as I can paste it elsewhere outlook etc and I capture named / timestamped files.  

I tend to capture sequences of files in one go hence not opening the editor for each capture by default

**Comment by Lakritzator** [comment]
Thanks, I can reproduce it and fix it for the next builds.

**Comment by Lakritzator** [comment]
Please try with 1.3.249, now available here: https://github.com/greenshot/greenshot/releases

**Comment by snowdej** [comment]
Bug is fixed - thank you
