### ISSUE TITLE
Feature Request: expose "AddTitle" ini setting in Imgur plugin SettingsForm

### ISSUE THREAD

**Issue by magus424** [greenshot/greenshot#4]
I discovered this feature on accident trying to figure out if I could clone my oauth token from one machine to another (since I can't see a way to re-auth) and would have liked to be able to turn this off ages ago.

Some window titles contain data I would rather not share (such as hostnames) and being able to tell it NOT to send it to Imgur is fantastic.

**Comment by JTBrinkmann** [comment]
that already exists. RIGHT BELOW the ImgurTokenSecret key in the default .ini file
```batch
; Is the title passed on to Imgur
AddTitle=True
```

**Comment by JTBrinkmann** [comment]
it's enabled by default (i.e. it doesn't send the title). see http://getgreenshot.org/2015/04/07/new-bugfix-release-greenshot-1-2-5/
Though I do agree there should be an option in the GUI, as I personally like to have it disable (i.e. send the title)

**Comment by magus424** [comment]
I've used greenshot since before that update, so it was enabled for me (enabled = send title)

For anyone else in my situation, a checkbox would be great :)

**Comment by Lakritzator** [comment]
Yes, it will come... As soon as I finish the UI for the configuration framework which I wrote for Greenshot (this can be found here:  https://github.com/dapplo/Dapplo.Config).

Most likely Greenshot 2.x
Greenshot will get an UI for the settings, probably similar to the one in Eclipse (example http://i.stack.imgur.com/Psy75.gif) where there is a tree of settings which you can search in. Also having an "user-level" where one can specify if they are expert or not.
As soon as this is there, Greenshot will automatically have a lot of new features as most were only available via the greenshot.ini

**Comment by Lakritzator** [comment]
We are removing the issues on github, as most people don't read and create feature request or report bugs here... and we already have an issue tracker. Just so you know.

https://greenshot.atlassian.net
