### ISSUE TITLE
Crop does not work anymore as before

### ISSUE THREAD

**Issue by mischlrebl** [greenshot/greenshot#404]
**Describe the bug**
the crop tool in the editor does not show the selection rectangle immedeately, only after

**To Reproduce**
Example steps to reproduce the behavior:
1. Capture '....'
2. Open Editor
3. Press 'C'
4. Select an area
5. The rectangle is not there anymore, only after releasing the mouse key

**Expected behavior**
while selecting the area, the selection rectangle should be shown

**Additional context**
btw, wasn't there an auto-crop item before in den edit menu?

**Comment by Ishmaeel** [comment]
Can confirm. Area selection by dragging no longer works. A fixed-size selection rectangle is created upon mouse release which can then be resized.

@mischlrebl, Auto-crop item is now hidden inside the crop type selection dropdown in the toolbar button.

**Comment by mischlrebl** [comment]
you are right with the crop tool, thank you
btw, wasn't there a shortcut too? I can't remember...

**Comment by Ishmaeel** [comment]
No, there wasn't a shortcut for auto crop.

**Comment by Lakritzator** [comment]
Please check the build (1.3.258) with the fix from @Christian-Schulz from here: https://github.com/greenshot/greenshot/releases
I'm currently still down with COVID...

**Comment by Ishmaeel** [comment]
@Lakritzator nicely fixed, thank you, and get well soon.

**Comment by Lakritzator** [comment]
> @Lakritzator nicely fixed, thank you, and get well soon.

@Christian-Schulz did the work 🙇‍♂️
