### ISSUE TITLE
Unable to open on Mac OS

### ISSUE THREAD

**Issue by Davie-C** [greenshot/greenshot#408]
**Describe the bug**
When trying to open on mac os the application won't open

**To Reproduce**
Download from Mac Store
Attempt to open

**Expected behavior**
The app should open

**Versions (please complete the following information):**
 - Greenshot version - 1.2.19
 - MacOS Monterey - 12.2 (Apple M1 Pro)

**Comment by Lakritzator** [comment]
I'm not sure how you got here, but this is the Greenshot for Windows repository.
I can not help you with OSX issues, for this you will need to report an issue in our JIRA.

It might be related to this here: https://greenshot.atlassian.net/jira/software/c/projects/MAC/issues/MAC-212
I do not know why it's still open, I'll ask for an update.

**Comment by Lakritzator** [comment]
I marked it "invalid" as it's really not the place, I can help you with issues on Windows.
