### ISSUE TITLE
problem when opening a folder

### ISSUE THREAD

**Issue by OmlineEditor** [greenshot/greenshot#410]
**To Reproduce**
open the program click show last capture location

**Expected behavior**
open the last image capture location

Software version: 1.2.9.129-RELEASE-569de711c0353860aaeb5e5ec4d272e383a101e9 (64 bit)
.NET runtime version: 4.0.30319.42000+
Time: 2022-05-26 14:28:51 +03:00
OS: unknown   (x64)  6.1 build 7601 revision 10000
GDI object count: 48
User object count: 26

Exception: System.ArgumentException
Message: Элемент уже добавлен. Ключ в словаре: "path"  Добавляемый ключ: 'path'

Stack:
   в System.Collections.ListDictionaryInternal.Add(Object key, Object value)
   в Greenshot.MainForm.Contextmenu_OpenRecent(Object sender, EventArgs eventArgs)
   в System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   в System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   в System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   в System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   в System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   в System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ToolStrip.WndProc(Message& m)
   в System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by OmlineEditor** [comment]
similarly for the latest stable version


Software version: 1.2.10.6-RELEASE-c2414cf0149a1475ea00520effc01b40087c225c (64 bit)
.NET runtime version: 4.0.30319.42000+

Time: 2022-05-26 14:47:13 +03:00
OS: unknown   (x64)  6.1 build 7601 revision 10000
GDI object count: 48
User object count: 27

Exception: System.ArgumentException
Message: Элемент уже добавлен. Ключ в словаре: "path"  Добавляемый ключ: 'path'

Stack:
   в System.Collections.ListDictionaryInternal.Add(Object key, Object value)
   в Greenshot.MainForm.Contextmenu_OpenRecent(Object sender, EventArgs eventArgs)
   в System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   в System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   в System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   в System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   в System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   в System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ToolStrip.WndProc(Message& m)
   в System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Ishmaeel** [comment]
This exception would actually be hiding the real error that prevents the opening of last capture location. During exception handling, this line would throw the exception because `path` would be added to exception detail twice:

https://github.com/greenshot/greenshot/blob/b92d79ed39c2689784e85ff4519d6dedb4601d2d/Greenshot/Forms/MainForm.cs#L1344

The faulty handling logic seem to have been fixed in the latest version (**1.3.258**).

@OmlineEditor, would you please try it again with the latest release and provide new logs, if it's still failing?

**Comment by OmlineEditor** [comment]
version 1.3.258 work OK. I'm waiting for the stable version
