### ISSUE TITLE
Let's remove the third-party DLL libraries from plugins' folders

### ISSUE THREAD

**Issue by d0vgan** [greenshot/greenshot#413]
**Is your feature request related to a problem? Please describe.**
Each plugin's folder has the whole set of the third-party DLL libraries: Dapplo.Windows.Multimedia.dll, Dapplo.Windows.Icons.dll, Dapplo.Windows.Shell32.dll, Dapplo.Windows.dll and so on. It adds redundancy and significantly increases the size of the Greenshot's folder.

**Describe the solution you'd like**
It should be enough to place all the third-party DLL libraries directly to the app's folder (near the Greenshot.exe) and to not have them under each plugin's folder.

**Describe alternatives you've considered**
In case of any requirement to have some third-party DLL library exactly near the Greenshot's plugin DLL library, I believe it can be solved by either adding a proper entry to the _.exe.config_ file or, in the worst case, by adding some code around loading of the dependencies..

**Comment by Lakritzator** [comment]
Good catch, I completely overlook that. 👍

**Comment by Lakritzator** [comment]
I just published 1.3.259, this should no longer have the copies of the "3rd party" libraries. (everything with Dapplo is mine anyway, so 3rd party makes me grin)

Maybe have a look and report back if everything works.

**Comment by d0vgan** [comment]
Thank you, it works!
