### ISSUE TITLE
Excessive pinging of https://getgreenshot.org/project-feed/

### ISSUE THREAD

**Issue by kentavv** [greenshot/greenshot#419]
Greenshot for Windows v. 1.2.10 Build 6, on Windows 10, pings https://getgreenshot.org/project-feed/ 541 times per day despite  "update check interval in days (0=no check)" set to 14.

This GitHub repository is for developers, if you want to report a bug for Greenshot as a user please do so in our JIRA issue system here: https://greenshot.atlassian.net/projects/BUGS/issues/filter=allopenissues

**Describe the bug**

**To Reproduce**
Example steps to reproduce the behavior:
1. Capture '....'
2. Open Editor
3. Add a line
4. Resize

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Greenshot version
 - Windows version

**Additional context**

**Comment by jklingen** [comment]
Hi @kentavv , sounds similar to this one: https://greenshot.atlassian.net/browse/SUPPORT-249

The only legit reason for this update check request going out more often than configured is if it fails (it will retry later then). Maybe in your scenario the request is permanently blocked e.g. by a firewall?

**Comment by kentavv** [comment]
Thank you for suggesting that, and thank you for responding here (I didn't want to create yet another account.) The traffic is observed at the router and there does not seem to be a firewall on the workstation. The /project-feed/ page loads fine in a browser. With 14-day check frequency set in the preferences, a ping occurs every five minutes. Maybe that's worth looking at? First concern was greenshot was sending snapshots externally. Glad to see greenshot is open source. I use it frequently everyday.

<img width="693" alt="Untitled" src="https://user-images.githubusercontent.com/6542480/175780295-cdfce146-8645-45f0-86ce-148866e056a3.png">
