### ISSUE TITLE
Send to Thunderbird Mail Client (I should be able to add destinations myself manually).

### ISSUE THREAD

**Issue by stixoffire** [greenshot/greenshot#427]
In the Capture to Selections I should have the option to send to Thunderbird. However better still would be to allow me to customize and select whatever program I desire to send to - then you need not fulfill 100's of requests - but only one request custom destinations.

**Comment by kp-gl** [comment]
I also don't see any gerneric "Send by mail" (...anymore? because the Features page of Greenshot mentions this)

**Comment by gitgrub** [comment]
My workflow is different, I prefer to work via clipboard if not saving the file to disk, that seems more flexible to me.
The reason is that I need to place the cursor to a position the screenshot will be placed beforehand, and after the capture I continue to work in the destination program.

Sending by mail might introduce TLS handshake complications, you could need credentials, I think that's another story.

**Comment by Lakritzator** [comment]
Greenshot will provide an "generic" MAPI-Client (as its called) destination if it can find one (and it's not outlook), this very much depends on how your mail client is installed. e.g. If you use a mail client inside the browser, this might not be found, as it's not registered in the registry and Greenshot will not know.

More about MAPI for Thunderbird here: http://kb.mozillazine.org/MAPI_Support and make sure Thunderbird is configured as the default mail client: http://kb.mozillazine.org/Default_mail_client

You can see if there is a MAPI client installed, by running powershell and paste the function here: https://community.idera.com/database-tools/powershell/powertips/b/tips/posts/finding-default-mapi-client

You can also use external commands to integrate pretty much anything, see here: https://getgreenshot.org/faq/how-can-a-screenshot-be-passed-to-another-software/

**Comment by stixoffire** [comment]
```
Get-MAPIClient

HasMapiClient Path                                                 MailTo                                                                     
------------- ----                                                 ------                                                                     
         True C:\Program Files\Mozilla Thunderbird\thunderbird.exe "C:\Program Files\Mozilla Thunderbird\thunderbird.exe" -osint -compose "%1"
```

So what I ended up using was just the executable path and left the args at {0} , admittingly  I had tried the command line switches first but the field turned red, so I put the switches in the arguments box and while it worked I got two mail message windows. 

I removed the switch arguments from the arguments and just left the executable in the application line. 
I noticed I can not select it as a default destination - until I restart the application.

With the powershell script probably could easily incorporate  AddMyDefaultMailClient   to the External Commands , or make the request on installation. 
Obviously web mail is so much different .. so maybe not that ..
