### ISSUE TITLE
need greenshot 1.3.122 (no content in .greenshot extension)

### ISSUE THREAD

**Issue by armia142** [greenshot/greenshot#430]
Hi guys, I need to have the version 1.3.122 exe as I'm using two versions the stable one as no installer version and the 1.3.122 for the zoom I download another version 1.3.249 after setup suddenly all the .greenshot files are blanked with no content in it please if anyone has the version please upload it again for me I can't find it at all ! or if there is any solution to get the content back please advice

**Comment by armia142** [comment]
@Lakritzator

**Comment by Lakritzator** [comment]
@armia142 ??

**Comment by armia142** [comment]
@Lakritzator could u help me with my problem?

**Comment by Lakritzator** [comment]
Maybe I can help but **pinging** is annoying, it doesn't add anything to the issue. Imagine everybody does this, for me this is bad etiquette especially for an free and open source repo.

I have a lot of other issues in other projects, and this (we also have them in jira), and have a life besides Greenshot.

I'll take a look when I have time, maybe tomorrow, depending on other issues.

**Comment by armia142** [comment]
uhh wow, I never expect that especially if I just mentioned u Sir I do respect u and your work but even after I waited for 3 days for a reply (I know I deserve this as its free and open source) I JUST want to grab ur attention noting that u are not the only person who has thing to do and not the only app, good luck in your life if you want to help that would be so generous from u; thanks

**Comment by Lakritzator** [comment]
I had a check, but I'm sorry to say that I cannot find a download for Greenshot 1.3.122
We do not want to keep beta/nightly/unstable builds available for ever, this makes the lists long and hard to understand.

But what you can do, Greenshot doesn't really need an installer, is just copy the contents of the Greenshot installation directory and copy it in a directory on the other system and start Greenshot from there.

Btw. It says in the "known issues": Greenshot will not read .greenshot files from other versions
This is something I am working on, but even if I make something it will only go back to official releases.

**Comment by armia142** [comment]
okay thanks for ur time I understand
