### ISSUE TITLE
The size obtained by "Capture region" is 1px larger

### ISSUE THREAD

**Issue by Rukoto** [greenshot/greenshot#432]
**Describe the bug**
The size obtained by "Capture region" is 1px larger

**Screenshots**
![Capture_region](https://user-images.githubusercontent.com/31055417/185290962-99588718-7e2e-4484-9599-219507d26e64.png)

**Versions**
 - Greenshot 1.3.270

**Comment by Lakritzator** [comment]
Oh, thanks for reporting this, that should not happen.
Did you also check if other versions have this issue?

**Comment by Rukoto** [comment]
Version 1.3.249 does not exhibit this bug.
Somewhere after this seems to be the problem.

**Comment by Lakritzator** [comment]
I finally had a bit of time to check what I changed after 1.3.249, and what immediately jumps into my eye is that right after that version I moved from internal spaghetti code for a lot of the low level Windows interop, to my better testable and more generic repository https://github.com/dapplo/Dapplo.Windows
So it must have to do with that change, I will figure it out.

**Comment by Lakritzator** [comment]
Huge change it was: https://github.com/greenshot/greenshot/commit/13e2e67e7c065e9657e60a9aa4834415f8430d80
