### ISSUE TITLE
Why Jira? Why Github?

### ISSUE THREAD

**Issue by aqoamann** [greenshot/greenshot#436]
I already have a GitHub account. I am already here. I have every useful function here in GitHub to simply report a bug, or request an issue, or help you with UX, coding, testing etc.

So... why Jira? Why should I open another account, with another password, another "notification" and "news" emails etc.?

Is GitHub not enough?

Kindly regards,
aqomann

**Comment by Lakritzator** [comment]
Hi,

it's a valid question, with pretty much a simple but long answer.

We started on Sourceforge, where we had everything, but the issue system there was horrible.
In 20214 we switched some of our tool stack to Atlassian, being BitBucket for our code repository and Jira for our issues. We also switched our build system to AppVeyor (I believe it was already done before the move), this all worked together and as we are producing open source it didn't cost us anything.

This was a multi-week effort, which doesn't make any money, in fact it distracted us from our development work. I blogged about it here: https://getgreenshot.org/2014/06/22/greenshot-switches-to-jira-for-bug-reports-and-feature-requests/

Sometime later we moved our sources away from BitBucket, to the more popular GitHub which finally got free for us in 2019, see here: https://github.blog/2019-01-07-new-year-new-github/

We moved our build system to Azure Pipelines some time afterwards, we waited while first it would have costed us money, later it wasn't in a usable state, but much later it was perfect for us (and this still works great).

We never moved our issues to GitHub, for the simple reasons:
* Jira worked
* Jira doesn't cost us
* It's a LOT of effort to move our issues from Jira to GitHub, who is going to pay for that? My free time...
* GitHub is seen more for technical people, it wasn't very accepted among "just" users.
* The feature set of github issues is less than that of Jira, so it would be a step back for us.

In the meantime, yeah GitHub is catching up, I have been considering to move our issues to GitHub issues... but the effort stopped me.

Maybe the feature set is enough, I didn't invest much time in a comparison yet, but does it really bring benefit to me or the project? We use GitHub for technical issues, to communicate with developers, and that works.

I understand your frustration, but for me issues are just work which isn't paid, one less user who doesn't report an issue with our product, one less user using our product, doesn't matter that much for a free project. Might sound hard, but I spent most of my time for Greenshot working on issues, getting more is not a goal.

Putting the bar to report issues down, would in fact make my life a living hell, and would stop Greenshot development to a halt.

Hope that explains it... You will notice when I do make the effort, who knows... one day 😁 
I will close this issue, as I answered your question and I do not see much benefit of keeping it open.

Best wishes,
Robin
