### ISSUE TITLE
Greenshot Icon no longer appear on my Windows Task Bar and so app cannot be invoked

### ISSUE THREAD

**Issue by MrDidz** [greenshot/greenshot#438]
I was recently forced to restore my Windows 10 Home software and as a result, lost all my best and most useful apps including Greenshot.

I have reinstalled Greenshot but downloading it from the website, but when I run it it simply dissappears into the background instead of placing an icon on my windows taskbar.  So, there is no way of telling that it is running, or invoking it to copy anything.  Simply press CTRL+C doesn;t seem to work.

I've tried telling pinning Greenshot to my Task Bar, but that just seems to pin the load icon and causes a 'Greenshot is already Running' message if clicked upon.  I've used Greenshot for years and this has never been problem in the past.  Usually when you start the app it places an icon on the Task Bar and clicking on it open the option menu.

Has something changed or do I need to do something to make it work properly?

**Comment by jklingen** [comment]
If you get the "Greenshot is already Running" message when you try to start Greenshot, it is running indeed. So it seems that the icon just is not displayed for some reason. You should be able to start a capture using Greenshot's hotkeys (e.g. `PrintScreen` for region capture).

I can only guess why the icon isn't where you expect it, maybe it is hidden behind that small chevron icon?
![image](https://user-images.githubusercontent.com/5475899/190903360-c500b89f-f0f9-4a3a-bb87-071457b0389c.png)
If you don't find it there, try having a look into your task bar settings, there are different options to configure visibility of icons in that area.

**Comment by MrDidz** [comment]
@jklingen 

Thank you for your reply and you are indeed correct.  It appears that restoring windows reset all the windows features to the default which apparently includes hiding most of the icons for apps that are running behind the chevron symbol.

I have managed to find the windows setting that stops this silly behaviour and so I'm back to a situation now where the Task Bar actually displays the icons of all the apps that are running.

Thank you for your help,
