### ISSUE TITLE
Capture region unavailable in v1.3.273

### ISSUE THREAD

**Issue by magl8** [greenshot/greenshot#441]
Capturing a region with version 1.3.273 gives unexpected results:
On Windows Server 2016, it produces an image with the selected size but a different position snippet of the screen.
On Windows 10 21H2, it produces a full screen image.
Reverting to previous version 1.3.270 fixes the problem.

**Comment by Lakritzator** [comment]
Oh damn, what the h**l is that... thanks for reporting.

Sorry, I didn't see this happen with my local development version.
I quickly deleted the download, so others are not wasting their time with it.

Need to check what it was, hope to have a working version soon.

**Comment by Lakritzator** [comment]
Ah got it, I screwed up. Used top & left instead of left and top.

**Comment by Lakritzator** [comment]
Don't know why I didn't see it, it didn't work in my dev setup either... sorry for wasting your time.

Thanks for reporting, I've created a new version 1.3.274 here: https://github.com/greenshot/greenshot/releases

**Comment by magl8** [comment]
Wow, thank you for turbo-fixing! Version 1.3.274 captures regions as expected again.
