### ISSUE TITLE
Ability to enable or disable the zoom option on capture region. 

### ISSUE THREAD

**Issue by Musa-Husseini** [greenshot/greenshot#445]
I think it would be a great feature to enable or disable the zoom option on the region capture through a key bind. Sometimes the zoom option is a bit annoying or irrelevant for a task, so having the option to remove it would be nice.

**Comment by Lakritzator** [comment]
Press the Z when in the region capture, it will remove the zoomer.

I'm not sure if it's documented somewhere, but did plan to document all keys soon.
