### ISSUE TITLE
dead project?

### ISSUE THREAD

**Issue by doubledgedboard** [greenshot/greenshot#452]
This app hasn't been released in over 5 years but I'm still seeing commits to the repo.

Do you want help building a release pipeline?

I love using Greenshot, but I'm considering moving off it if the app team is unable to release fixes or improvements.

**Comment by Lakritzator** [comment]
If you see commits coming in, this means the project is not dead. You can even install those newest versions, the release pipeline works fine. There are a few issues that need to be solved before an official release is made.

So it will be released when it is released, but you are welcome to move to something different.

**Comment by doubledgedboard** [comment]
I have professional experience as a build/release engineer so please excuse my perspective, but if you have new commits and you haven't released in 5 years then the project is effectively dead.

Thanks for the response, though. Hope you figure it out!

**Comment by doubledgedboard** [comment]
> conversations of this kind are distracting and demotivating.

You haven't released in 5 years. Sounds like you need motivation or maybe a reality check. It's not just about the time between releases, it's about being able to push security fixes etc. If you can't release new builds because you can't get the code signed, then your release pipeline is effectively blocked/dead. If you can't even ship a single one line change (comment), your release process is dead.

You can criticize my response or be defensive, but it doesn't change the fact that 5 years is a criminally long release cycle.

**Comment by jklingen** [comment]
I didn't say that the situation is fine, I think @Lakritzator explained it well above. I don't see anything to argue about.

I just wondered why you create a ticket to ask a question, when it rather seems that you already know and other answers are wrong. And I wanted to point out that OS maintainers might feel offended by such conversations.

**Comment by Neustradamus** [comment]
Linked to: https://github.com/greenshot/greenshot/issues/163

**Comment by Neustradamus** [comment]
Now, since 2017-09-13: 7 years, 8 months, 1 day) without a new build:
- https://github.com/greenshot/greenshot/issues/163

**Comment by jklingen** [comment]
Please refer to https://github.com/greenshot/greenshot/issues/163#issuecomment-2898610705
