### ISSUE TITLE
Feature Request: Too small icons in the editor

### ISSUE THREAD

**Issue by robozb** [greenshot/greenshot#464]
Anyway thanks for this great software

![SmallIcons](https://user-images.githubusercontent.com/8656998/210709615-7119f48c-f3c2-4510-b4e3-b605cbcadeb1.JPG)

**Comment by swaipa** [comment]
> Is It possible to enlarge the icons anywhere?

<img width="340" alt="image" src="https://user-images.githubusercontent.com/9133169/213440530-9e550996-6dd3-48bf-935b-013b8ae5e3dd.png">

**Comment by robozb** [comment]
Thanks!
