### ISSUE TITLE
Sorry

### ISSUE THREAD

**Issue by WilsonBradley** [greenshot/greenshot#467]
Sorry for the NOOB question, but there is no Github [Discussion] section for Greenshot, so....

So I noticed multiple system that have greenshot installed are having random lagging. Not saying it's GreenShot per say, however was looking to get latest update and noticed 2017.. Then in Github was worked on last month. 
Where to get latest compiled version?

**Comment by Christian-Schulz** [comment]
You can use the pre release. The latest version is from 5. Oktober 2022.
https://github.com/greenshot/greenshot/releases

**Comment by jklingen** [comment]
Thanks @Christian-Schulz 

@WilsonBradley I assume that this link is what you're looking for. If not, please let us know.
