### ISSUE TITLE
Security question: "acropalypse" and greenshot

### ISSUE THREAD

**Issue by AlexErrant** [greenshot/greenshot#475]
It was recently disclosed that [Pixel phones](https://www.bleepingcomputer.com/news/security/google-pixel-flaw-allowed-recovery-of-redacted-cropped-images/) and the [Snip & Sketch tool on Win10/11 ](https://www.bleepingcomputer.com/news/microsoft/windows-11-snipping-tool-privacy-bug-exposes-cropped-image-content/) don't necessarily truncate cropped data, leading to the possibility of "uncropping" an image.

Does Greenshot have this vulnerability?

**Comment by Lakritzator** [comment]
I've looked into this, and I have no indication or reason to believe we have the same vulnability.
As far as I understood, it's a but in the file handling and the effected applications just overwrite a part of a file and leaves the other stuff in. Greenshot really overwrites the files, so there is a completely new file in place, all other stuff is gone.

Also checked in case of cropping, and writing to the same file, you can really see the filesize go down.
Also if you open a capture in the editor, save it, and would crop this image and save it as another file, the size is much smaler.

But you are welcome to validate this yourself.
