### ISSUE TITLE
THIS software opens spammy windows on the PC, disable it!!!!

### ISSUE THREAD

**Issue by rxhvtjv** [greenshot/greenshot#476]
YOU KNOW WHAT I AM TALKING ABOUT.

This horrible software triggers windows on a silent install! Who would ever approve this! You should be ashamed of doing this nonsense, no other software opens browser on silent install!!!!!!!!!!!! I wish I could donate -$1000 or ddos your trash website!!!!!!! Seeing this is despicable, stop forever opening the website!!!! STOP.

I do NOT care about your donations, you people don't deserve a cent. REMOVE the popup. 

REMOVE IT. 

That is not a question. Do not reply telling me nonsense about donations!!!

Remove the popup!!!!!

NO one will miss it

REMOVE IT

REMOVE IT

**Comment by rxhvtjv** [comment]
I hate garbage greenshot taking me this much time and effort to dismiss!!!!!!! THIS WAS SO MUCH NONSENSE I HAD TO SEE AND DISMISS ON 800+ INSTALLS YOU PEOPLE HAVE DONE NOTHING BUT WASTE MY TIME!!!!!!

REMOVE

THE 

POPUP

**Comment by rxhvtjv** [comment]
I have taken the issue up to our head of IT, I am writing so many enraged emails to get this trash out of our entire company!!!!!!!


NO OTHER SOFTWARE DOES THIS

YOU OPENING BROWSER ON SILENT INSTALL IS A SECURITY RISK AND STRAIGHT UP SPAM

REMOVE IT.

**Comment by rxhvtjv** [comment]
I HATE GREENSHOT AND ALL THAT COMES WITH IT. 

SPAM

UNWANTED POPUPS

STOP

**Comment by rxhvtjv** [comment]
I will do my absolute best to advise literal hundreds of people against this software. 

This just cost me so much time I can't believe it.

I had to close some several hundreds of browsers because of you. I hate you people.

**Comment by Lakritzator** [comment]
Get a live.
