### ISSUE TITLE
Feature Request: option to add a frame around captured area.

### ISSUE THREAD

**Issue by TimCarloPPI** [greenshot/greenshot#491]
I did a little search before posting, sorry if this has already made the request list.

Our IT team loves Greenshot for documenting processes.  For aesthetics I typically add a frame around whatever I capture when I paste into an email.  We are moving to a IT help desk / service management tool and unfortunately there's no option yet to add a frame around what gets pasted into that editor.  Of course I could ask them to provide an option to frame the image. 

So, simply, asking you folks to consider adding a setting/option/feature that adds a frame/boarder or a selection of various frame/boarder styles to the captured image. 

THANKS!!!

**Comment by GitMensch** [comment]
I suggest to close this and follow the project guideline, also noted in the repo's "about":

> Report bugs & features go here: https://greenshot.atlassian.net/

**Comment by TimCarloPPI** [comment]
Moving request to official request system.
