### ISSUE TITLE
Copy shortcut via Ctrl+C instead Ctrl+Shift+C

### ISSUE THREAD

**Issue by JulienMalbault** [greenshot/greenshot#554]
So many softwares use copy shortcut "Ctrl+C". In greenshot is Ctrl+Shift+C
Could you change it ? 
Or at least make updated by ini file.

**Comment by FF-Brown** [comment]
@JulienMalbault I'm guessing you're talking about when the editor is open?
If so, Ctrl+C does copy. It copies items in the editor, like text boxes, shapes, other images, etc. Copying the whole screenshot to the clipboard (Ctrl+Shift+C) is more like an export operation, so to me it makes sense for Ctrl+C to be reserved for copying items within the editor. This is the same behavior you would see in most other applications. Ctrl+C would copy an item in the editor, and to export the whole thing you'd have either a different shortcut or a menu button.

**Comment by JulienMalbault** [comment]
@FF-Brown thank you for your reactivity and your answer. It make sense. thank you.

**Comment by sean-nitric** [comment]
I would really prefer to reverse these hotkeys. I very often take a screenshot, and an arrow drawing attention to the key part and then copy into an email. I rarely need to copy items in the editor
