### ISSUE TITLE
Generic email button gone with Office Plugin installed

### ISSUE THREAD

**Issue by Wyatts** [greenshot/greenshot#6]
They rolled out a new version of greenshot at work (1.2.8.12) and it has the Office plugin.  This caused old email button to disappear, but the Outlook button inserts the image it into the editor as though I would make the mistake of sending an HTML email.

To get a proper attachment now, one must either save it manually and attach separately or make an external command shortcut for Outlook (/a "{1}").

**Comment by Lakritzator** [comment]
I guess you updated from a much older version of Greenshot, as we changed this behavior longer ago. The plan was that we add a setting to the UI for changing the behavior, but somehow this never happened... 

What you can try, is to add the following line to the greenshot.ini:
OutlookEmailFormat=Text

That should be directly under the line with [Office]
Here you can read on how to find the greenshot.ini file: http://getgreenshot.org/faq/where-does-greenshot-store-its-configuration-settings/
Before you change anything, make sure Greenshot is not running.

Hope this helps, I will work on the UI now....

**Comment by Lakritzator** [comment]
Did it help?

**Comment by Lakritzator** [comment]
Closing due to a lack or response.
