### ISSUE TITLE
${NUM} increments itself.

### ISSUE THREAD

**Issue by ericBG** [greenshot/greenshot#7]
Whenever I go to the Expert options and set ${NUM} to a specific value, I then close it and then come back to it just to see it be set to that value + 1, or sometimes more erratically +2.

**Comment by Lakritzator** [comment]
Strickly speaking it doesn't increment itself without a reason, it's incremented as soon as a filename is created. This happens for various reasons, some internally. An example is when showing the Save as dialog, without saving. But even if there is a reason, for the user this should work as expected.

We have Jira for features/bugs which are not directly code releated, on github we mainly handle direct code issues.

I will handle this ticket in this feature request: https://greenshot.atlassian.net/browse/FEATURE-824
would that be okay?

**Comment by Lakritzator** [comment]
As there is no response, I will close this issue.
It will be tracked via this feature: https://greenshot.atlassian.net/browse/FEATURE-824
