### ISSUE TITLE
language-cs-CZ.xml update

### ISSUE THREAD

**Issue by PetrToman** [greenshot/greenshot#9]
Hello,
Greenshot's Transifex translation project seems not to be active (https://www.transifex.com/greenshot/greenshot/), so I'm using this issue to send and update of CZ language file. [language-cs-CZ.zip](https://github.com/greenshot/greenshot/files/171514/language-cs-CZ.zip)

**Comment by Lakritzator** [comment]
Hey, thanks a lot.

I certainly can put this into the project, but it would be even cooler if you could create a pull-request on release/1.2.9

This way your contribution is clearly visible...

Let me know how you want to have it.

Best wishes,
Robin

**Comment by PetrToman** [comment]
Ok. Sorry if I haven't done it properly, it is my first pull request on Github O:-)

**Comment by Lakritzator** [comment]
No problem, and no... you haven't done it properly. :)
You should create a fork, change the file in the branch release/1.2.9 and than create a pull request which will allow me to pull your changes into our repository.

The pull request you made, doesn't have the language changes, and it looks like you want to have us pull branch release/1.2.9 into branch "master". Not a good idea :)

Let me know if you have problems.

**Comment by PetrToman** [comment]
Ok, second service. I hope RTFM did help... thanks for patience :-)

**Comment by Lakritzator** [comment]
No problem at all, I'm very grateful for every help we get.
And I just prefer pull-requests otherwise your contribution is not visible.

Looks very good, will merge!

Keep up the great work, and we hope in the near future to use something like Transifex... (that was a test project)
